#include "MetalBackend.hpp"

#include "GameWindow.hpp"
#include "Supervisor.hpp"
#include "i18n.hpp"
#include "utils.hpp"

// metal-cpp single-header includes NS::Object, MTL::Device, CA::MetalLayer,
// and MTL4::CommandQueue. The single header pulls Foundation + Metal +
// QuartzCore together; this is the recommended integration approach.
//
// The *_PRIVATE_IMPLEMENTATION defines must be set before including the
// single header — they expand the inline objc_msgSend shims into real
// symbols in this TU. Define them in exactly one translation unit.
#define NS_PRIVATE_IMPLEMENTATION
#define MTL_PRIVATE_IMPLEMENTATION
#define CA_PRIVATE_IMPLEMENTATION
#include "thirdparty/metal-cpp/SingleHeader/Metal.hpp"

#include <SDL2/SDL.h>
#include <SDL2/SDL_syswm.h>

#include <cstdio>
#include <cstring>

// ============================================================================
// M2: MSL shaders — translation of src/graphics/ff.vert + ff.frag.
// Embedded as C++ string literals and compiled at runtime via
// device->newLibraryWithSource(). This mirrors the WebGL backend, which
// embeds the GLSL via autogenerated/Embeds.hpp and compiles it at startup.
//
// Binding model:
//   buffer(0) — MetalUniforms (vertex + fragment stage)
//   buffer(1) — vertex buffer (vertex stage; stage_in fetches attributes
//               from this buffer using the offset/stride in the PSO vertex
//               descriptor). Index 1 avoids the M2 hazard where the vertex
//               descriptor and the uniform buffer both claimed index 0.
//   texture(0) — bound texture (fragment stage; M4 populates)
//   sampler(0) — bound sampler (fragment stage; M4 populates)
//
// The frag shader's NO_VERTEX_BUFFER / NO_FOG / USE_FRAG_DEPTH preprocessor
// branches from the GLSL are translated to the default path (envDiffuse used
// as fragArg2, fog applied, alpha-test via discard). EoSD always uses these
// defaults; the GL backend's omittedUniforms set excludes fog only when the
// context lacks it. The Metal path always has fog available.
// ============================================================================
static const char *kMSLVertexSource = R"MSL(
#include <metal_stdlib>
using namespace metal;

// Keep this layout in sync with MetalUniforms in MetalBackend.hpp.
// std140-style explicit packing; metal-cpp's MTLBuffer contents are raw bytes.
struct Uniforms
{
    float4x4 modelviewMatrix;
    float4x4 projectionMatrix;
    float4x4 textureMatrix;
    float4   envDiffuse;
    float4   fogColor;
    int      useTexCoords;
    int      useDiffuse;
    int      colorOp;
    float    fogNear;
    float    fogFar;
};

struct VertexIn
{
    float3 position  [[attribute(0)]];
    float2 texCoords [[attribute(1)]];
    float4 diffuse   [[attribute(2)]];
};

struct VertexOut
{
    float4 position     [[position]];
    float2 texCoords;
    float4 diffuse;
    float  viewZ;
};

// The vertex stage pulls attributes from buffer(1) via the stage_in vertex
// descriptor (configured per-PSO with the stride/offsets for the current
// vertex layout); the uniform struct is at buffer(0). The position attribute
// is float3 but the game's VertexTex1Xyzrhw has a float4 position (xyzw) —
// the descriptor reads only xyz via Float3, and the shader reconstructs the
// vec4 with `float4(in.position, 1.0)`.
vertex VertexOut ff_vertex(VertexIn in [[stage_in]],
                           constant Uniforms &u [[buffer(0)]])
{
    VertexOut out;
    out.texCoords = (u.textureMatrix * float4(in.texCoords, 1.0, 1.0)).xy;
    out.diffuse   = in.diffuse;
    float4 viewCoordinates = u.modelviewMatrix * float4(in.position, 1.0);
    out.viewZ     = viewCoordinates.z;
    out.position  = u.projectionMatrix * viewCoordinates;
    return out;
}
)MSL";

static const char *kMSLFragmentSource = R"MSL(
#include <metal_stdlib>
using namespace metal;

struct Uniforms
{
    float4x4 modelviewMatrix;
    float4x4 projectionMatrix;
    float4x4 textureMatrix;
    float4   envDiffuse;
    float4   fogColor;
    int      useTexCoords;
    int      useDiffuse;
    int      colorOp;
    float    fogNear;
    float    fogFar;
};

struct VertexOut
{
    float4 position     [[position]];
    float2 texCoords;
    float4 diffuse;
    float  viewZ;
};

#define OP_MODULATE 0
#define OP_ADD      1
#define OP_REPLACE  2

constant float alphaThreshold = 4.0 / 255.0;

fragment float4 ff_fragment(VertexOut in     [[stage_in]],
                            constant Uniforms &u [[buffer(0)]],
                            texture2d<float> tex [[texture(0)]],
                            sampler smp [[sampler(0)]])
{
    float4 fragColor = float4(0.0, 0.0, 0.0, 0.0);
    float4 fragArg1;
    float4 fragArg2;

    if (u.useTexCoords != 0)
    {
        fragArg1 = tex.sample(smp, in.texCoords);
    }
    else
    {
        fragArg1 = in.diffuse;
    }
    fragArg2 = u.envDiffuse;

    if (u.colorOp == OP_MODULATE)
    {
        fragColor = fragArg1 * fragArg2;
    }
    else if (u.colorOp == OP_ADD)
    {
        // EoSD: add applies to RGB only; alpha still modulates.
        fragColor.rgb = min(fragArg1.rgb + fragArg2.rgb, float3(1.0, 1.0, 1.0));
        fragColor.a   = fragArg1.a * fragArg2.a;
    }
    else // OP_REPLACE
    {
        fragColor = fragArg1;
    }

    // Fog. View-space depth from the vertex shader.
    float fogCoefficient = (u.fogFar - in.viewZ) / (u.fogFar - u.fogNear);
    fogCoefficient = clamp(fogCoefficient, 0.0, 1.0);
    fragColor.rgb = mix(u.fogColor.rgb, fragColor.rgb, fogCoefficient);

    if (fragColor.a < alphaThreshold)
    {
        discard_fragment();
    }
    return fragColor;
}
)MSL";

GfxInterface *MetalBackend::Create()
{
    MetalBackend *interface = new MetalBackend;

    SDL_Init(SDL_INIT_VIDEO);

    u32 flags = SDL_WINDOW_METAL | SDL_WINDOW_SHOWN;
    i32 height = GAME_WINDOW_HEIGHT_REAL;
    i32 width = GAME_WINDOW_WIDTH_REAL;
    i32 x = SDL_WINDOWPOS_UNDEFINED;
    i32 y = SDL_WINDOWPOS_UNDEFINED;

    if (g_Supervisor.cfg.windowed == 0)
    {
        flags |= SDL_WINDOW_FULLSCREEN;
    }

    SDL_Window *window = SDL_CreateWindow(TH_WINDOW_TITLE, x, y, width, height, flags);
    interface->window = window;
    if (window == NULL)
    {
        utils::DebugPrint2("MetalBackend: SDL_CreateWindow failed: %s", SDL_GetError());
        delete interface;
        return nullptr;
    }

    if (!interface->Init())
    {
        delete interface;
        return nullptr;
    }

    utils::DebugPrint2("MetalBackend: using MTL::Device + MTL::CommandQueue");
    return interface;
}

bool MetalBackend::Init()
{
    NS::AutoreleasePool *pool = NS::AutoreleasePool::alloc()->init();

    // SDL_Metal_CreateView returns an opaque SDL_MetalView (a CAMetalLayer-backed
    // NSView on macOS). SDL_Metal_GetLayer unwraps it to the raw CAMetalLayer*.
    this->metalView = SDL_Metal_CreateView(this->window);
    if (this->metalView == NULL)
    {
        utils::DebugPrint2("MetalBackend: SDL_Metal_CreateView failed: %s", SDL_GetError());
        pool->drain();
        return false;
    }

    this->layer = static_cast<CA::MetalLayer *>(SDL_Metal_GetLayer(this->metalView));
    if (this->layer == nullptr)
    {
        utils::DebugPrint2("MetalBackend: SDL_Metal_GetLayer returned null");
        pool->drain();
        return false;
    }

    // Create the system default device and bind it to the layer. The layer's
    // device must match the device used to render its drawables.
    this->device = MTL::CreateSystemDefaultDevice();
    if (this->device == nullptr)
    {
        utils::DebugPrint2("MetalBackend: MTL::CreateSystemDefaultDevice returned null (Metal not available)");
        pool->drain();
        return false;
    }
    this->layer->setDevice(this->device);

    // Configure the CAMetalLayer for presentation. BGRA8Unorm matches the
    // pipeline color attachment format we'll create in M2. framebufferOnly=NO
    // allows ReadPixels (M5) to sample the drawable texture via getBytes;
    // the cost is losing some GPU compression on the drawable, which is
    // negligible at EoSD's 640×480 target. displaySyncEnabled=YES caps
    // presentation to the display refresh rate.
    this->layer->setPixelFormat(MTL::PixelFormatBGRA8Unorm);
    this->layer->setMaximumDrawableCount(2);
    this->layer->setFramebufferOnly(false);
    this->layer->setDisplaySyncEnabled(true);
    // Note: metal-cpp's CA::MetalLayer binding does not expose setOpaque in
    // this version. The layer is opaque in practice for a fullscreen game;
    // direct-to-display eligibility is not needed for M1's clear-screen check.
    // drawableSize is set per-frame in SwapBuffers() from the window size, so
    // resize is handled without a separate windowDidResize: hook (the game
    // window is fixed at GAME_WINDOW_*_REAL).

    // Command queue. The goal doc targeted MTL4::CommandQueue, but MTL4 requires
    // macOS 26 (Tahoe); this dev machine is macOS 15 (Sequoia), where the
    // MTL4 selector throws at runtime. Per user direction, the port uses the
    // MTL (Metal 3) command queue, which runs on every supported macOS.
    // Migrating to MTL4 on a Tahoe target is a mechanical swap.
    this->commandQueue = this->device->newCommandQueue();
    if (this->commandQueue == nullptr)
    {
        utils::DebugPrint2("MetalBackend: newCommandQueue returned null");
        pool->drain();
        return false;
    }

    // M2: build the render pipeline, depth-stencil state, uniform buffer,
    // and persistent depth texture. Failure of any sub-step is fatal — the
    // backend can't render without a pipeline.
    if (!this->InitPipeline())
    {
        pool->drain();
        return false;
    }

    // Initialize uniforms to identity matrices + sensible defaults. The WebGL
    // backend does the same in its Init(): identity modelview/projection/
    // texture, fogFar=1. envDiffuse/fogColor default to opaque black via the
    // zero-init here; the game sets real values before drawing.
    this->uniforms.modelviewMatrix.Identity();
    this->uniforms.projectionMatrix.Identity();
    this->uniforms.textureMatrix.Identity();
    this->uniforms.envDiffuse = ZunVec4(0.0f, 0.0f, 0.0f, 1.0f);
    this->uniforms.fogColor = ZunVec4(0.0f, 0.0f, 0.0f, 1.0f);
    this->uniforms.useTexCoords = 0;
    this->uniforms.useDiffuse = 0;
    this->uniforms.colorOp = COLOR_OP_MODULATE;
    this->uniforms.fogNear = 0.0f;
    this->uniforms.fogFar = 1.0f;

    // Seed the first ring slot with the initial uniform values so the very
    // first frame's draws (before any SetXxx) have sane state. Reset the
    // ring offset to 0 afterwards — the first Draw will write slot 0 again
    // with the actual per-draw uniforms.
    this->FlushUniforms();
    this->frameUniformOffset = 0;

    pool->drain();
    return true;
}

// M2: build the MSL library, vertex/fragment functions, render pipeline state,
// depth-stencil state, uniform buffer, and the persistent depth texture.
//
// All metal-cpp factory calls below follow the autorelease rule documented in
// the team memory: methods whose name contains new/alloc/copy/Create return
// owned (+1) objects we must release(); others return autoreleased (+0)
// objects we hold as raw pointers within this autorelease pool scope.
bool MetalBackend::InitPipeline()
{
    NS::AutoreleasePool *pool = NS::AutoreleasePool::alloc()->init();
    bool ok = false;

    NS::Error *fragCompileError = nullptr;
    MTL::Library *fragLib = nullptr;

    // Compile the embedded MSL sources. Each shader is compiled as its own
    // library — they declare the same Uniforms/VertexOut structs, so
    // concatenating would trigger redefinition errors. newLibrary returns
    // owned (+1) Libraries — released in Exit().
    NS::Error *compileError = nullptr;
    MTL::CompileOptions *options = MTL::CompileOptions::alloc()->init();
    NS::String *vertexSrc = NS::String::string(kMSLVertexSource, NS::UTF8StringEncoding);
    NS::String *fragSrc = NS::String::string(kMSLFragmentSource, NS::UTF8StringEncoding);
    MTL::Library *vertLib = this->device->newLibrary(vertexSrc, options, &compileError);
    if (vertLib == nullptr)
    {
        if (compileError != nullptr)
        {
            utils::DebugPrint2("MetalBackend: vertex MSL compile failed: %s",
                                compileError->localizedDescription()->utf8String());
        }
        else
        {
            utils::DebugPrint2("MetalBackend: vertex MSL compile failed (no error)");
        }
        options->release();
        goto cleanup;
    }
    vertLib->setLabel(NS::String::string("th06 ff vertex", NS::UTF8StringEncoding));

    // Reuse the same CompileOptions for the fragment library.
    fragLib = this->device->newLibrary(fragSrc, options, &fragCompileError);
    options->release();
    if (fragLib == nullptr)
    {
        if (fragCompileError != nullptr)
        {
            utils::DebugPrint2("MetalBackend: fragment MSL compile failed: %s",
                                fragCompileError->localizedDescription()->utf8String());
        }
        else
        {
            utils::DebugPrint2("MetalBackend: fragment MSL compile failed (no error)");
        }
        vertLib->release();
        goto cleanup;
    }
    fragLib->setLabel(NS::String::string("th06 ff fragment", NS::UTF8StringEncoding));

    // Keep shaderLibrary pointing at the vertex library for the label/debug
    // grouping; the fragment library is held only long enough to look up the
    // function below. Both are released in cleanup.
    this->shaderLibrary = vertLib;
    this->shaderLibrary->setLabel(NS::String::string("th06 ff shaders", NS::UTF8StringEncoding));

    // Library::newFunction(name) returns an owned (+1) Function.
    this->vertexFunction = vertLib->newFunction(
        NS::String::string("ff_vertex", NS::UTF8StringEncoding));
    this->fragmentFunction = fragLib->newFunction(
        NS::String::string("ff_fragment", NS::UTF8StringEncoding));
    fragLib->release();
    if (this->vertexFunction == nullptr || this->fragmentFunction == nullptr)
    {
        utils::DebugPrint2("MetalBackend: function lookup failed");
        goto cleanup;
    }

    // M3: No PSO is baked here. PSOs are built on demand in GetPipeline()
    // keyed by VertexLayoutKey, because the game interleaves draws with
    // different vertex strides/offsets (VertexTex1Xyzrhw, VertexTex1DiffuseXyz,
    // VertexTex1DiffuseXyzrhw, RenderVertexInfo). InitPipeline only builds
    // the shaders, depth-stencil state, and persistent buffers.

    // M5: depth-stencil states are now built lazily in GetDepthStencilState,
    // keyed by (depthWrite, depthCompare). The game toggles SetDepthMask and
    // SetDepthFunc per sprite group, so caching one state per tuple avoids
    // rebuilding the descriptor each call. The default state (LEQUAL + write)
    // is created on the first Draw. InitPipeline no longer bakes one here.

    // M4: persistent linear sampler. The game calls SetTextureFilter() once
    // per CreateTextureObject (matching the GL backend's GL_LINEAR magFilter).
    // One sampler covers all draws — the game never requests a different
    // filter. samplerDescriptor returns autoreleased (+0); newSamplerState
    // returns owned (+1) — released in Exit().
    {
        MTL::SamplerDescriptor *samplerDesc = MTL::SamplerDescriptor::alloc()->init();
        samplerDesc->setSAddressMode(MTL::SamplerAddressModeClampToEdge);
        samplerDesc->setTAddressMode(MTL::SamplerAddressModeClampToEdge);
        samplerDesc->setMagFilter(MTL::SamplerMinMagFilterLinear);
        samplerDesc->setMinFilter(MTL::SamplerMinMagFilterLinear);
        samplerDesc->setMipFilter(MTL::SamplerMipFilterNotMipmapped);
        samplerDesc->setLabel(NS::String::string("th06 linear", NS::UTF8StringEncoding));
        this->samplerState = this->device->newSamplerState(samplerDesc);
        samplerDesc->release();
    }
    if (this->samplerState == nullptr)
    {
        utils::DebugPrint2("MetalBackend: newSamplerState failed");
        goto cleanup;
    }

    // M3: Uniform ring buffer. One MetalUniforms slot per potential draw call
    // this frame. The game updates matrices per sprite, so each Draw needs its
    // own slice; the CPU writes the current `uniforms` into the slice at
    // frameUniformOffset and the encoder binds it. Shared storage mode =
    // CPU-visible, GPU-readable. newBuffer returns owned (+1) — released in
    // Exit().
    this->uniformBufferSize = sizeof(MetalUniforms) * kMaxDrawsPerFrame;
    this->uniformBuffer = this->device->newBuffer(this->uniformBufferSize,
                                                    MTL::ResourceOptionCPUCacheModeDefault);
    if (this->uniformBuffer == nullptr)
    {
        utils::DebugPrint2("MetalBackend: uniform newBuffer failed");
        goto cleanup;
    }
    this->uniformBuffer->setLabel(NS::String::string("th06 uniforms ring", NS::UTF8StringEncoding));

    // M3: Persistent vertex buffer. One large Shared-storage buffer bumped
    // per frame. The game's largest single draw is AnmManager::vertexBuffer
    // (98304 verts); at 28 bytes/vert (largest layout) that's ~2.75 MB. Round
    // up to 4 MB to give headroom for multiple large draws in one frame.
    this->vertexBufferSize = 4 * 1024 * 1024;
    this->vertexBuffer = this->device->newBuffer(this->vertexBufferSize,
                                                  MTL::ResourceOptionCPUCacheModeDefault);
    if (this->vertexBuffer == nullptr)
    {
        utils::DebugPrint2("MetalBackend: vertex newBuffer failed");
        goto cleanup;
    }
    this->vertexBuffer->setLabel(NS::String::string("th06 vertex ring", NS::UTF8StringEncoding));
    this->frameVertexOffset = 0;
    this->frameUniformOffset = 0;

    // Persistent depth texture — allocated lazily in EnsureDepthTexture on
    // the first frame, when the drawable size is known. M1 allocated a
    // throwaway per-frame; M2 reuses one across frames and only reallocates
    // on resize.
    this->depthTexture = nullptr;
    this->depthTextureWidth = 0;
    this->depthTextureHeight = 0;

    ok = true;

cleanup:
    pool->drain();
    return ok;
}

// M3/M5: build (or fetch from cache) a render pipeline state for the given
// vertex layout + blend configuration. One PSO per unique
// (stride, positionOffset, texCoordOffset, diffuseOffset, blendMode). Cached
// for the backend's lifetime; released in Exit().
MTL::RenderPipelineState *MetalBackend::GetPipeline(const PipelineKey &key)
{
    auto it = this->pipelineCache.find(key);
    if (it != this->pipelineCache.end())
    {
        return it->second;
    }

    NS::AutoreleasePool *pool = NS::AutoreleasePool::alloc()->init();
    MTL::RenderPipelineState *pso = nullptr;
    MTL::VertexDescriptor *vertexDescriptor = nullptr;
    MTL::RenderPipelineDescriptor *pipelineDesc = nullptr;
    NS::Error *pipelineError = nullptr;

    // Vertex descriptor — bakes the per-attribute offsets and stride from
    // `key` into the PSO. All three attributes read from buffer(1) — the
    // persistent vertex buffer bound at draw time. The position attribute is
    // Float3 even though some game layouts (VertexTex1Xyzrhw) have a float4
    // position; Metal reads only the first 3 floats, and the shader
    // reconstructs the vec4 with w=1.0. The diffuse attribute is
    // UChar4Normalized — game stores it as a packed 32-bit ColorData.
    vertexDescriptor = MTL::VertexDescriptor::alloc()->init();
    vertexDescriptor->attributes()->object(0)->setFormat(MTL::VertexFormatFloat3);
    vertexDescriptor->attributes()->object(0)->setBufferIndex(kVertexBufferIndex);
    vertexDescriptor->attributes()->object(0)->setOffset(key.positionOffset);
    vertexDescriptor->attributes()->object(1)->setFormat(MTL::VertexFormatFloat2);
    vertexDescriptor->attributes()->object(1)->setBufferIndex(kVertexBufferIndex);
    vertexDescriptor->attributes()->object(1)->setOffset(key.texCoordOffset);
    vertexDescriptor->attributes()->object(2)->setFormat(MTL::VertexFormatUChar4Normalized);
    vertexDescriptor->attributes()->object(2)->setBufferIndex(kVertexBufferIndex);
    vertexDescriptor->attributes()->object(2)->setOffset(key.diffuseOffset);
    vertexDescriptor->layouts()->object(kVertexBufferIndex)->setStride(key.stride);

    pipelineDesc = MTL::RenderPipelineDescriptor::alloc()->init();
    pipelineDesc->setVertexFunction(this->vertexFunction);
    pipelineDesc->setFragmentFunction(this->fragmentFunction);
    pipelineDesc->setVertexDescriptor(vertexDescriptor);
    MTL::RenderPipelineColorAttachmentDescriptor *colorAtt =
        pipelineDesc->colorAttachments()->object(0);
    colorAtt->setPixelFormat(MTL::PixelFormatBGRA8Unorm);

    // M5: blend configuration. Metal bakes blend factors into the PSO's color
    // attachment — there is no separate blend state object. The game uses two
    // blend modes (SetBlendMode in AnmManager.cpp:699,704):
    //   BLEND_INV_SRC_ALPHA -> glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
    //   BLEND_ONE           -> glBlendFunc(GL_SRC_ALPHA, GL_ONE)
    // blendMode of -1 means blend is disabled (Enable(CAPS_BLEND) was never
    // called or the default state). When disabled, blending is off and the
    // fragment shader's output is written directly.
    if (key.blendMode >= 0)
    {
        colorAtt->setBlendingEnabled(true);
        colorAtt->setSourceRGBBlendFactor(MTL::BlendFactorSourceAlpha);
        colorAtt->setDestinationRGBBlendFactor(
            key.blendMode == BLEND_ONE ? MTL::BlendFactorOne
                                       : MTL::BlendFactorOneMinusSourceAlpha);
        // Alpha blend: src*srcAlpha + dst*(1-srcAlpha). Matches GL's
        // default for glBlendFunc when only RGB factors are specified —
        // GL applies the same factors to alpha unless glBlendFuncSeparate
        // is used, which EoSD does not.
        colorAtt->setSourceAlphaBlendFactor(MTL::BlendFactorSourceAlpha);
        colorAtt->setDestinationAlphaBlendFactor(
            key.blendMode == BLEND_ONE ? MTL::BlendFactorOne
                                       : MTL::BlendFactorOneMinusSourceAlpha);
        colorAtt->setRgbBlendOperation(MTL::BlendOperationAdd);
        colorAtt->setAlphaBlendOperation(MTL::BlendOperationAdd);
    }
    // else: blendingEnabled defaults to false.

    pipelineDesc->setDepthAttachmentPixelFormat(MTL::PixelFormatDepth32Float);
    pipelineDesc->setStencilAttachmentPixelFormat(MTL::PixelFormatInvalid);
    {
        char label[112];
        const char *blendName = (key.blendMode < 0) ? "off"
                                : (key.blendMode == BLEND_ONE) ? "one" : "invSrcAlpha";
        std::snprintf(label, sizeof(label),
                      "th06 ff pipeline (stride=%lu pos=%lu tex=%lu diff=%lu blend=%s)",
                      (unsigned long)key.stride, (unsigned long)key.positionOffset,
                      (unsigned long)key.texCoordOffset, (unsigned long)key.diffuseOffset,
                      blendName);
        pipelineDesc->setLabel(NS::String::string(label, NS::UTF8StringEncoding));
    }

    pso = this->device->newRenderPipelineState(pipelineDesc, &pipelineError);
    if (pso == nullptr)
    {
        if (pipelineError != nullptr)
        {
            utils::DebugPrint2("MetalBackend: newRenderPipelineState failed: %s",
                                pipelineError->localizedDescription()->utf8String());
        }
        else
        {
            utils::DebugPrint2("MetalBackend: newRenderPipelineState failed (no error)");
        }
    }
    else
    {
        this->pipelineCache[key] = pso;
    }

    if (vertexDescriptor != nullptr) vertexDescriptor->release();
    if (pipelineDesc != nullptr) pipelineDesc->release();
    pool->drain();
    return pso;
}

// M5: build (or fetch from cache) a depth-stencil state for the given
// (write, compare) tuple. One state per unique combination. Cached for the
// backend's lifetime; released in Exit().
MTL::DepthStencilState *MetalBackend::GetDepthStencilState(const DepthStencilKey &key)
{
    auto it = this->depthStencilCache.find(key);
    if (it != this->depthStencilCache.end())
    {
        return it->second;
    }

    NS::AutoreleasePool *pool = NS::AutoreleasePool::alloc()->init();
    MTL::DepthStencilDescriptor *desc = MTL::DepthStencilDescriptor::alloc()->init();
    desc->setDepthWriteEnabled(key.depthWriteEnabled);
    desc->setDepthCompareFunction((MTL::CompareFunction)key.depthCompare);
    {
        char label[80];
        const char *cmpName = (key.depthCompare == MTL::CompareFunctionAlways)  ? "always"
                              : (key.depthCompare == MTL::CompareFunctionLessEqual) ? "lequal"
                              : "other";
        std::snprintf(label, sizeof(label), "th06 depth (%s, %s)",
                      key.depthWriteEnabled ? "write" : "nowrite", cmpName);
        desc->setLabel(NS::String::string(label, NS::UTF8StringEncoding));
    }
    MTL::DepthStencilState *state = this->device->newDepthStencilState(desc);
    desc->release();
    pool->drain();
    if (state != nullptr)
    {
        this->depthStencilCache[key] = state;
    }
    else
    {
        utils::DebugPrint2("MetalBackend: newDepthStencilState failed");
    }
    return state;
}

// M3: copy `count` vertices from the CPU pointer recorded by
// SetAttributePointer into the persistent vertex buffer, returning the GPU
// offset of the copied slice. The base pointer is taken from the POSITION
// attribute (always present); the per-attribute offsets are baked into the
// PSO via `key`. The slice is bumped into the ring at frameVertexOffset.
NS::UInteger MetalBackend::CopyVertexData(const PipelineKey &key, i32 start, i32 count)
{
    NS::UInteger bytes = (NS::UInteger)key.stride * (NS::UInteger)count;
    if (bytes == 0)
    {
        return 0;
    }

    // Bump the ring. If we'd overflow, wrap to 0 — the previous frame's GPU
    // work has completed by the time we're writing this frame (the command
    // buffer from the last SwapBuffers was committed and the next drawable
    // acquired synchronously in BeginFrame). HARDCODED: assumes single-buffer
    // framing; if we move to double-buffered with <2 frame latency, this
    // needs a fence.
    if (this->frameVertexOffset + bytes > this->vertexBufferSize)
    {
        this->frameVertexOffset = 0;
    }
    NS::UInteger dstOffset = this->frameVertexOffset;
    this->frameVertexOffset += bytes;

    // The CPU pointer recorded for POSITION is the base of the vertex array.
    // `start` indexes into it; the per-attribute offsets are baked into the
    // PSO so we only need to copy the raw vertex bytes here.
    const u8 *src = (const u8 *)this->attribs[VERTEX_ARRAY_POSITION].ptr
                    + (std::size_t)start * key.stride;
    void *dst = (u8 *)this->vertexBuffer->contents() + dstOffset;
    std::memcpy(dst, src, bytes);

    return dstOffset;
}

// Copy the CPU-side `uniforms` struct into the GPU-visible uniform buffer at
// the current frame uniform ring offset, returning the byte offset of the
// slice. Called once per Draw so each draw sees its own uniforms snapshot
// (the game updates matrices per sprite). The buffer is Shared storage mode —
// contents() returns a CPU pointer we can memcpy into directly.
//
// At frame open (BeginFrame) the ring offset is reset to 0. Each Draw bumps
// it by sizeof(MetalUniforms). If we'd overflow the ring, wrap to 0 — the
// previous frame's GPU work has completed by the time we're writing this
// frame (the command buffer from the last SwapBuffers was committed and the
// next drawable acquired synchronously in BeginFrame).
NS::UInteger MetalBackend::FlushUniforms()
{
    if (this->uniformBuffer == nullptr)
    {
        return 0;
    }

    // Round the per-draw uniform slice up to a 16-byte boundary. Metal
    // requires buffer offsets bound at a vertex/fragement stage to be a
    // multiple of 16; sizeof(MetalUniforms) is 244 (3*64 + 2*16 + 3*4 + 2*4),
    // so naive bumping produces offsets 244, 488, 732... all of which violate
    // the alignment. Padding each slice to 256 keeps the ring 16-aligned and
    // leaves headroom in the slice for future struct growth.
    static constexpr NS::UInteger kUniformSlice = (sizeof(MetalUniforms) + 15u) & ~NS::UInteger(15u);

    if (this->frameUniformOffset + kUniformSlice > this->uniformBufferSize)
    {
        this->frameUniformOffset = 0;
    }
    NS::UInteger offset = this->frameUniformOffset;
    this->frameUniformOffset += kUniformSlice;

    void *gpu = (u8 *)this->uniformBuffer->contents() + offset;
    if (gpu != nullptr)
    {
        std::memcpy(gpu, &this->uniforms, sizeof(MetalUniforms));
    }
    return offset;
}

// (Re)allocate the persistent depth texture if the drawable size has changed.
// Called from SwapBuffers before opening the render pass. The depth texture
// is Private storage (GPU-local only) — it's a render target, never mapped.
void MetalBackend::EnsureDepthTexture(NS::UInteger width, NS::UInteger height)
{
    if (this->depthTexture != nullptr &&
        this->depthTextureWidth == width &&
        this->depthTextureHeight == height)
    {
        return;
    }

    if (this->depthTexture != nullptr)
    {
        this->depthTexture->release();
        this->depthTexture = nullptr;
    }

    if (width == 0 || height == 0)
    {
        return;
    }

    MTL::TextureDescriptor *desc = MTL::TextureDescriptor::alloc()->init();
    desc->setTextureType(MTL::TextureType2D);
    desc->setPixelFormat(MTL::PixelFormatDepth32Float);
    desc->setWidth(width);
    desc->setHeight(height);
    desc->setStorageMode(MTL::StorageModePrivate);
    desc->setUsage(MTL::TextureUsageRenderTarget);
    this->depthTexture = this->device->newTexture(desc);
    if (this->depthTexture != nullptr)
    {
        this->depthTexture->setLabel(NS::String::string("th06 depth", NS::UTF8StringEncoding));
        this->depthTextureWidth = width;
        this->depthTextureHeight = height;
    }
    else
    {
        utils::DebugPrint2("MetalBackend: depth newTexture failed (%lux%lu)",
                            (unsigned long)width, (unsigned long)height);
        this->depthTextureWidth = 0;
        this->depthTextureHeight = 0;
    }
    desc->release();
}

void MetalBackend::Exit()
{
    // metal-cpp objects are reference-counted via NS::Object; release() drops
    // our reference. The autorelease pool isn't required for release() itself
    // but keeps any transient objects created during teardown clean.
    NS::AutoreleasePool *pool = NS::AutoreleasePool::alloc()->init();

    // Tear down any in-flight frame state first — if Exit() is called mid-frame
    // (e.g. on error), the encoder/command buffer/drawable must be dropped
    // before the device and command queue go away. These are autoreleased (+0)
    // objects captured during the frame; do NOT release() them — the pool
    // drain below handles it. Just end any open encoding and clear the slots.
    if (this->currentRenderEncoder != nullptr)
    {
        this->currentRenderEncoder->endEncoding();
        this->currentRenderEncoder = nullptr;
    }
    this->currentCommandBuffer = nullptr;
    this->currentDrawable = nullptr;
    if (this->framePool != nullptr)
    {
        this->framePool->drain();
        this->framePool = nullptr;
    }

    // M2/M3 resources — all owned (+1) from new*/alloc()->init()/Create in
    // InitPipeline. Release in reverse-of-creation order. Vertex ring buffer,
    // uniform ring buffer, depth texture, depth-stencil, cached PSOs,
    // functions, library.
    if (this->vertexBuffer != nullptr)
    {
        this->vertexBuffer->release();
        this->vertexBuffer = nullptr;
        this->vertexBufferSize = 0;
        this->frameVertexOffset = 0;
    }
    if (this->uniformBuffer != nullptr)
    {
        this->uniformBuffer->release();
        this->uniformBuffer = nullptr;
        this->uniformBufferSize = 0;
        this->frameUniformOffset = 0;
    }
    if (this->depthTexture != nullptr)
    {
        this->depthTexture->release();
        this->depthTexture = nullptr;
        this->depthTextureWidth = 0;
        this->depthTextureHeight = 0;
    }
    // M5: depth-stencil states are now cached per (write, compare) tuple.
    // Release all cached entries; each was created with +1 from
    // newDepthStencilState in GetDepthStencilState.
    for (auto &kv : this->depthStencilCache)
    {
        if (kv.second != nullptr)
        {
            kv.second->release();
        }
    }
    this->depthStencilCache.clear();
    // M4: release all live textures + the persistent sampler. Each
    // MTLTexture in the pool was created with +1 from newTexture in
    // SetTextureImage. Sentinel slots (0x1) are not real objects — skip.
    for (u32 i = 0; i < kMaxTextures; i++)
    {
        MTL::Texture *tex = this->textures[i];
        if (tex != nullptr && tex != reinterpret_cast<MTL::Texture *>(0x1))
        {
            tex->release();
        }
        this->textures[i] = nullptr;
    }
    this->currentTexture = nullptr;
    this->currentTextureHandle = 0;
    if (this->samplerState != nullptr)
    {
        this->samplerState->release();
        this->samplerState = nullptr;
    }
    // M3: release all cached PSOs. Each was created with +1 from
    // newRenderPipelineState in GetPipeline.
    for (auto &kv : this->pipelineCache)
    {
        if (kv.second != nullptr)
        {
            kv.second->release();
        }
    }
    this->pipelineCache.clear();
    if (this->fragmentFunction != nullptr)
    {
        this->fragmentFunction->release();
        this->fragmentFunction = nullptr;
    }
    if (this->vertexFunction != nullptr)
    {
        this->vertexFunction->release();
        this->vertexFunction = nullptr;
    }
    if (this->shaderLibrary != nullptr)
    {
        this->shaderLibrary->release();
        this->shaderLibrary = nullptr;
    }

    if (this->commandQueue != nullptr)
    {
        this->commandQueue->release();
        this->commandQueue = nullptr;
    }
    if (this->device != nullptr)
    {
        this->device->release();
        this->device = nullptr;
    }
    // layer is owned by the NSView backing metalView; do not release it.
    this->layer = nullptr;

    if (this->metalView != nullptr)
    {
        SDL_Metal_DestroyView(this->metalView);
        this->metalView = nullptr;
    }
    if (this->window != nullptr)
    {
        SDL_DestroyWindow(this->window);
        this->window = nullptr;
    }

    pool->drain();
}

// ============================================================================
// STUB(M0): All GfxInterface methods below are no-ops. They are tagged with
// STUB(Mx) comments indicating which milestone will implement each. The grep
// pattern `grep "STUB(M" src/graphics/MetalBackend.cpp` lists all deferred
// work.
// ============================================================================

void MetalBackend::SetFogRange(f32 nearPlane, f32 farPlane)
{
    // M2: store in uniforms; flushed to GPU in SwapBuffers (and once at Init).
    this->uniforms.fogNear = nearPlane;
    this->uniforms.fogFar = farPlane;
}

void MetalBackend::SetFogColor(ZunColor color)
{
    // ZunColor is a u32 packed 0xAARRGGBB (COLOR_ALPHA_MASK etc.). The GL
    // backend unpacks to normalized floats in the same order (R=16, G=8, B=0,
    // A=24) — see WebGL.cpp SetFogColor. Match that here.
    this->uniforms.fogColor = ZunVec4(((color >> 16) & 0xFF) / 255.0f,
                                       ((color >> 8) & 0xFF) / 255.0f,
                                       ((color >> 0) & 0xFF) / 255.0f,
                                       ((color >> 24) & 0xFF) / 255.0f);
}

void MetalBackend::ToggleVertexAttribute(u8 attr, bool enable)
{
    // M3: ToggleVertexAttribute maps to the useTexCoords/useDiffuse uniforms
    // consumed by the fragment shader. The vertex descriptor always wires all
    // three attributes; when an attribute is "disabled", the shader ignores
    // the interpolated value because the corresponding flag is 0.
    //
    // The GL backend toggles glEnableVertexAttribArray, which matters there
    // because a disabled attribute reads a constant current value instead of
    // per-vertex data. In Metal, the attribute is always read per-vertex —
    // the game ensures the underlying buffer has valid data for the attribute
    // even when disabled (it always sets the diffuse pointer even when
    // VERTEX_ATTR_DIFFUSE is off, and the fragment shader gates on the flag).
    // We match the WebGL backend's uniform mapping exactly.
    if (attr & VERTEX_ATTR_TEX_COORD)
    {
        this->uniforms.useTexCoords = enable ? 1 : 0;
    }
    if (attr & VERTEX_ATTR_DIFFUSE)
    {
        this->uniforms.useDiffuse = enable ? 1 : 0;
    }
}

void MetalBackend::SetAttributePointer(VertexAttributeArrays attr, std::size_t stride, void *ptr)
{
    // M3: record the CPU pointer + stride for this attribute. Draw() derives
    // the per-attribute offset within a vertex from the difference between
    // this ptr and the POSITION attribute's ptr (all three attributes are
    // fields of one struct, so ptr_attr - ptr_pos = attrOffset).
    //
    // The game calls SetAttributePointer once per attribute per draw, all
    // with the same stride. We record each individually; Draw() picks up the
    // base from VERTEX_ARRAY_POSITION.
    if ((u32)attr < 3)
    {
        this->attribs[attr].ptr = ptr;
        this->attribs[attr].stride = stride;
    }
}

void MetalBackend::SetColorOp(TextureOpComponent component, ColorOp op)
{
    // M2: colorOp is a single int uniform consumed by the fragment shader.
    // The component argument is ignored on the GL backend too — EoSD only
    // uses the RGB path.
    (void)component;
    this->uniforms.colorOp = (i32)op;
}

void MetalBackend::SetTextureFactor(ZunColor factor)
{
    // M2: envDiffuse uniform (the GL backend calls this "envDiffuse"; the
    // shader multiplies fragArg2 by it). Same unpacking as SetFogColor.
    this->uniforms.envDiffuse = ZunVec4(((factor >> 16) & 0xFF) / 255.0f,
                                         ((factor >> 8) & 0xFF) / 255.0f,
                                         ((factor >> 0) & 0xFF) / 255.0f,
                                         ((factor >> 24) & 0xFF) / 255.0f);
}

void MetalBackend::SetTransformMatrix(TransformMatrix type, const ZunMatrix &matrix)
{
    // M2: route to the right slot in the uniforms struct. The GL backend's
    // matrixUniformEnum maps MATRIX_MODEL and MATRIX_VIEW both to MODELVIEW
    // (EoSD never sets them independently); mirror that here.
    switch (type)
    {
    case MATRIX_MODEL:
    case MATRIX_VIEW:
        this->uniforms.modelviewMatrix = matrix;
        break;
    case MATRIX_PROJECTION:
        this->uniforms.projectionMatrix = matrix;
        break;
    case MATRIX_TEXTURE:
        this->uniforms.textureMatrix = matrix;
        break;
    }
}

void MetalBackend::SetTextureFilter()
{
    // M4: the persistent linear sampler is created once in InitPipeline.
    // The game only ever requests GL_LINEAR (see FixedFunctionGL::SetTextureFilter),
    // so there's nothing to update here — the sampler is already bound at
    // draw time in Draw(). Kept as a no-op to satisfy the GfxInterface
    // contract; the actual sampler state lives in this->samplerState.
}

void MetalBackend::GetViewport(u32 *viewport)
{
    // M5: return cached viewport. The game (ZunViewport::Get) reads
    // viewPortGet[0..3] = (x, y, width, height) and applies its own
    // GL→D3D y flip math, so we return the raw cached values unchanged.
    if (viewport != nullptr)
    {
        viewport[0] = (u32)this->viewport[0];
        viewport[1] = (u32)this->viewport[1];
        viewport[2] = (u32)this->viewport[2];
        viewport[3] = (u32)this->viewport[3];
    }
}

void MetalBackend::GetDepthRange(f32 *depthRange)
{
    // M5: return cached depth range (near, far).
    if (depthRange != nullptr)
    {
        depthRange[0] = this->depthRange[0];
        depthRange[1] = this->depthRange[1];
    }
}

void MetalBackend::SetViewport(i32 x, i32 y, i32 width, i32 height)
{
    // M5: cache viewport. The game passes Y in GL bottom-origin convention
    // (ZunViewport::Set flips Y before calling). We store the raw value and
    // flip Y to Metal top-origin when applying to the encoder in
    // ApplyViewport. GetViewport returns the raw cached value so the game's
    // reverse-flip math works unchanged.
    this->viewport[0] = x;
    this->viewport[1] = y;
    this->viewport[2] = width;
    this->viewport[3] = height;
    this->viewportDirty = true;
}

void MetalBackend::SetDepthRange(f32 nearPlane, f32 farPlane)
{
    // M5: cache depth range. Applied to the encoder in ApplyViewport via
    // setDepthClipPlane (Metal's name for the depth range mapping).
    this->depthRange[0] = nearPlane;
    this->depthRange[1] = farPlane;
    this->viewportDirty = true;
}

void MetalBackend::Enable(Capabilities cap)
{
    // M5: enable-only (GfxInterface has no Disable method). The game calls
    // Enable(CAPS_BLEND) and Enable(CAPS_DEPTH_TEST) once at init
    // (GameWindow.cpp:499,505) and never disables them. Set the flag; Draw()
    // applies it when selecting the PSO blend config and depth-stencil state.
    switch (cap)
    {
    case CAPS_BLEND:
        this->blendEnabled = true;
        break;
    case CAPS_DEPTH_TEST:
        this->depthTestEnabled = true;
        break;
    }
}

bool MetalBackend::HasError()
{
    // STUB(M0): HasError — no error tracking yet
    return false;
}

void MetalBackend::SetBlendMode(BlendMode mode)
{
    // M5: store the requested blend mode. Draw() bakes it into the PSO key
    // so the right blend configuration is selected from the pipeline cache.
    // The game toggles between BLEND_INV_SRC_ALPHA (default sprites) and
    // BLEND_ONE (additive sprite groups) per AnmManager sprite batch
    // (AnmManager.cpp:699,704).
    this->currentBlendMode = (i32)mode;
}

void MetalBackend::SetDepthMask(bool enable)
{
    // M5: store depth-write flag. Draw() combines this with depthFunc and
    // depthTestEnabled to look up the cached MTL::DepthStencilState.
    this->depthMaskEnabled = enable;
}

void MetalBackend::SetDepthFunc(DepthFunc func)
{
    // M5: store depth-compare function. Draw() maps this to
    // MTL::CompareFunction when looking up the depth-stencil state:
    //   DEPTH_FUNC_LEQUAL -> MTL::CompareFunctionLessEqual
    //   DEPTH_FUNC_ALWAYS -> MTL::CompareFunctionAlways
    this->depthFunc = (i32)func;
}

void MetalBackend::SetClearDepth(f32 depth)
{
    this->clearDepth = depth;
}

void MetalBackend::SetClearColor(f32 r, f32 g, f32 b, f32 a)
{
    this->clearColor[0] = r;
    this->clearColor[1] = g;
    this->clearColor[2] = b;
    this->clearColor[3] = a;
}

void MetalBackend::Clear(u32 clearBits)
{
    // M1: defer the actual clear to SwapBuffers(). The game calls Clear()
    // multiple times per frame — once with color|depth at frame start, and
    // mid-frame depth-only clears during the draw chain. Metal can't cheaply
    // clear mid-pass, so we OR the requested bits and apply them once at pass
    // open. This is sufficient for M1's "solid color in window" success
    // criterion. M5 will revisit mid-frame clears if the game needs them.
    this->pendingClearBits |= clearBits;
}

GfxTextureHandle MetalBackend::CreateTexture()
{
    // M4: hand out a fresh handle id 1..kMaxTextures. The game treats 0 as
    // "no texture" (GfxTextureHandle default-constructs to 0), so ids start
    // at 1 and index textures[id-1]. We never reuse ids — the game creates
    // ~264 textures over its lifetime (AnmManager::textures array size),
    // well under the 512 slot budget. If we ever exhaust the pool this
    // returns handle 0, which Draw() treats as "no texture bound".
    for (u32 i = 0; i < kMaxTextures; i++)
    {
        if (this->textures[i] == nullptr)
        {
            // Mark the slot as claimed with a sentinel so SetTextureImage
            // knows it's a live handle even before the MTLTexture is created.
            // We use a non-null placeholder so a second CreateTexture before
            // SetTextureImage doesn't hand out the same slot.
            // Note: the actual MTLTexture is created in SetTextureImage,
            // since CreateTexture itself has no size/format info.
            this->textures[i] = reinterpret_cast<MTL::Texture *>(0x1);
            return GfxTextureHandle(i + 1);
        }
    }
    utils::DebugPrint2("MetalBackend: texture pool exhausted (%u slots)", kMaxTextures);
    return GfxTextureHandle(0);
}

void MetalBackend::BindTexture(GfxTextureHandle handle)
{
    // M4: record the bound handle. The MTLTexture pointer is resolved at
    // Draw() time from textures[handle-1] — it may be a sentinel (0x1) if
    // SetTextureImage hasn't run yet, in which case Draw() binds no texture
    // and the shader's useTexCoords=0 path falls back to the diffuse color.
    if (handle == 0 || (u32)handle > kMaxTextures)
    {
        this->currentTextureHandle = 0;
        this->currentTexture = nullptr;
        return;
    }
    this->currentTextureHandle = (u32)handle;
    MTL::Texture *tex = this->textures[(u32)handle - 1];
    this->currentTexture = (tex == reinterpret_cast<MTL::Texture *>(0x1)) ? nullptr : tex;
}

void MetalBackend::DeleteTexture(GfxTextureHandle handle)
{
    // M4: release the MTLTexture and clear the slot. The slot may still hold
    // the sentinel (0x1) if SetTextureImage was never called — just clear it.
    if (handle == 0 || (u32)handle > kMaxTextures)
    {
        return;
    }
    MTL::Texture *tex = this->textures[(u32)handle - 1];
    if (tex != nullptr && tex != reinterpret_cast<MTL::Texture *>(0x1))
    {
        tex->release();
    }
    this->textures[(u32)handle - 1] = nullptr;
    if (this->currentTexture == tex)
    {
        this->currentTexture = nullptr;
    }
}

void MetalBackend::SetTextureImage(u32 width, u32 height, PixelFormat fmt, PixelDataType type,
                                   const void *data)
{
    // M4: create (or replace) the MTLTexture for the currently bound handle.
    // All incoming formats are normalized to RGBA8Unorm on the CPU before
    // upload — the MSL fragment shader samples texture(0) as float4 and the
    // PSO color attachment is BGRA8Unorm, so RGBA8 source data maps cleanly.
    //
    // The game calls CreateTextureObject() -> CreateTexture + BindTexture +
    // SetTextureFilter before SetTextureImage, so currentTexture handle is
    // already claimed (sentinel 0x1 in the slot). We resolve the slot from
    // the bound handle by scanning — the GL backend doesn't pass the handle
    // to SetTextureImage, relying on the "currently bound" convention.
    // Find the slot by matching the sentinel.
    //
    // StorageModeShared: CPU-writable via contents(), GPU-readable. On Apple
    // Silicon unified memory this is zero-copy. Usage ShaderRead — the game
    // never renders into textures.

    if (width == 0 || height == 0)
    {
        return;
    }

    // Resolve the slot from the bound handle. The game's pattern is
    // CreateTexture (slot <- sentinel 0x1) -> BindTexture (records handle)
    // -> SetTextureImage (this function). currentTextureHandle points at
    // the slot we need to fill. If no handle is bound, bail.
    if (this->currentTextureHandle == 0)
    {
        utils::DebugPrint2("MetalBackend: SetTextureImage with no bound texture");
        return;
    }
    u32 slot = this->currentTextureHandle - 1;

    // Compute source bytes per pixel from the engine's PixelFormat/PixelDataType.
    // RGB/RGBA with UNSIGNED_BYTE = 3/4 bytes; 16-bit packed types = 2 bytes.
    u32 srcBpp;
    bool isPacked16;
    switch (type)
    {
    case PIXEL_UNSIGNED_BYTE:
        srcBpp = (fmt == PIXEL_RGBA) ? 4 : 3;
        isPacked16 = false;
        break;
    case PIXEL_UNSIGNED_SHORT_5_5_5_1:
    case PIXEL_UNSIGNED_SHORT_5_6_5:
    case PIXEL_UNSIGNED_SHORT_4_4_4_4:
        srcBpp = 2;
        isPacked16 = true;
        break;
    default:
        utils::DebugPrint2("MetalBackend: SetTextureImage unsupported PixelDataType %d", (int)type);
        return;
    }

    // Release any prior MTLTexture in this slot (re-upload path).
    MTL::Texture *old = this->textures[slot];
    if (old != nullptr && old != reinterpret_cast<MTL::Texture *>(0x1))
    {
        old->release();
        this->textures[slot] = nullptr;
    }

    // Allocate the RGBA8 destination texture.
    MTL::TextureDescriptor *desc = MTL::TextureDescriptor::alloc()->init();
    desc->setTextureType(MTL::TextureType2D);
    desc->setPixelFormat(MTL::PixelFormatRGBA8Unorm);
    desc->setWidth((NS::UInteger)width);
    desc->setHeight((NS::UInteger)height);
    // mipLevelCount defaults to 1 in MTL::TextureDescriptor — no setter in
    // this metal-cpp version. Single-mip is what we want anyway (the game
    // never generates mipmaps).
    desc->setStorageMode(MTL::StorageModeShared);
    desc->setUsage(MTL::TextureUsageShaderRead);
    MTL::Texture *tex = this->device->newTexture(desc);
    desc->release();
    if (tex == nullptr)
    {
        utils::DebugPrint2("MetalBackend: newTexture failed (%ux%u)", width, height);
        this->textures[slot] = nullptr;
        return;
    }
    {
        char label[64];
        std::snprintf(label, sizeof(label), "th06 texture #%u (%ux%u RGBA8)",
                      slot + 1, width, height);
        tex->setLabel(NS::String::string(label, NS::UTF8StringEncoding));
    }

    // Convert source pixels to RGBA8 and upload. If data is NULL (the game
    // uses this for CreateEmptyTexture), skip the upload — the texture is
    // created with uninitialized memory, which is fine because the game
    // overwrites it via SetTextureSubImage before sampling.
    if (data != nullptr)
    {
        const u8 *src = (const u8 *)data;
        NS::UInteger dstRowBytes = (NS::UInteger)width * 4;
        NS::UInteger srcRowBytes = (NS::UInteger)width * srcBpp;

        // Allocate a conversion buffer for one row. For UNSIGNED_BYTE RGBA
        // we can upload directly; for everything else convert row-by-row.
        if (fmt == PIXEL_RGBA && !isPacked16)
        {
            // Direct upload — source is already RGBA8.
            MTL::Region region = MTL::Region::Make2D(0, 0, (NS::UInteger)width, (NS::UInteger)height);
            tex->replaceRegion(region, 0, src, srcRowBytes);
        }
        else
        {
            u8 *row = new u8[dstRowBytes];
            for (u32 y = 0; y < height; y++)
            {
                const u8 *srcRow = src + (NS::UInteger)y * srcRowBytes;
                for (u32 x = 0; x < width; x++)
                {
                    u8 *dstPx = row + (NS::UInteger)x * 4;
                    if (isPacked16)
                    {
                        u16 p = (u16)srcRow[(NS::UInteger)x * 2]
                                | ((u16)srcRow[(NS::UInteger)x * 2 + 1] << 8);
                        u8 r, g, b, a;
                        switch (type)
                        {
                        case PIXEL_UNSIGNED_SHORT_5_6_5:
                            r = (p >> 11) & 0x1F; g = (p >> 5) & 0x3F; b = p & 0x1F;
                            // Replicate high bits into low bits to expand 5/6-bit to 8-bit.
                            dstPx[0] = (r << 3) | (r >> 2);
                            dstPx[1] = (g << 2) | (g >> 4);
                            dstPx[2] = (b << 3) | (b >> 2);
                            dstPx[3] = 0xFF;
                            break;
                        case PIXEL_UNSIGNED_SHORT_5_5_5_1:
                            r = (p >> 11) & 0x1F; g = (p >> 6) & 0x1F;
                            b = (p >> 1) & 0x1F; a = p & 0x1;
                            dstPx[0] = (r << 3) | (r >> 2);
                            dstPx[1] = (g << 3) | (g >> 2);
                            dstPx[2] = (b << 3) | (b >> 2);
                            dstPx[3] = a ? 0xFF : 0x00;
                            break;
                        case PIXEL_UNSIGNED_SHORT_4_4_4_4:
                            r = (p >> 12) & 0xF; g = (p >> 8) & 0xF;
                            b = (p >> 4) & 0xF; a = p & 0xF;
                            dstPx[0] = (r << 4) | r;
                            dstPx[1] = (g << 4) | g;
                            dstPx[2] = (b << 4) | b;
                            dstPx[3] = (a << 4) | a;
                            break;
                        default:
                            dstPx[0] = dstPx[1] = dstPx[2] = 0;
                            dstPx[3] = 0xFF;
                            break;
                        }
                    }
                    else
                    {
                        // PIXEL_RGB, UNSIGNED_BYTE -> RGBA8 (alpha = 0xFF).
                        dstPx[0] = srcRow[(NS::UInteger)x * 3 + 0];
                        dstPx[1] = srcRow[(NS::UInteger)x * 3 + 1];
                        dstPx[2] = srcRow[(NS::UInteger)x * 3 + 2];
                        dstPx[3] = 0xFF;
                    }
                }
                MTL::Region region = MTL::Region::Make2D(0, (NS::UInteger)y,
                                                          (NS::UInteger)width, 1);
                tex->replaceRegion(region, 0, row, dstRowBytes);
            }
            delete[] row;
        }
    }

    this->textures[slot] = tex;
    // If the bound handle points at this slot, update currentTexture so
    // the next Draw picks up the freshly uploaded texture.
    if (this->currentTexture == nullptr || this->currentTexture == reinterpret_cast<MTL::Texture *>(0x1))
    {
        this->currentTexture = tex;
    }
}

void MetalBackend::SetTextureSubImage(i32 xoffset, i32 yoffset, i32 width, i32 height, const void *data)
{
    // M5: replace a sub-region of the currently bound texture. The game's
    // only caller (AnmManager::ApplySurfaceToColorBuffer, line 2177) uploads
    // RGB UNSIGNED_BYTE data into a texture previously created via
    // SetTextureImage with PIXEL_RGB + UNSIGNED_BYTE (null data). Our
    // SetTextureImage normalizes all uploads to RGBA8, so the destination
    // MTLTexture is RGBA8Unorm — we must convert RGB→RGBA8 here too.
    //
    // Metal's replaceRegion is a CPU-side blit into the Shared-storage
    // texture's contents; no encoder needed. The region is clamped to the
    // texture's bounds by Metal.
    if (this->currentTexture == nullptr || data == nullptr || width <= 0 || height <= 0)
    {
        return;
    }

    NS::UInteger texWidth = this->currentTexture->width();
    NS::UInteger texHeight = this->currentTexture->height();
    if ((NS::UInteger)(xoffset + width) > texWidth || (NS::UInteger)(yoffset + height) > texHeight)
    {
        utils::DebugPrint2("MetalBackend: SetTextureSubImage region out of bounds (%d+%d > %lu, %d+%d > %lu)",
                            xoffset, width, (unsigned long)texWidth,
                            yoffset, height, (unsigned long)texHeight);
        return;
    }

    // Convert RGB8 source → RGBA8 row-by-row. The source stride is width*3;
    // the destination stride is width*4. replaceRegion takes per-row bytes
    // for the destination.
    const u8 *src = (const u8 *)data;
    NS::UInteger dstRowBytes = (NS::UInteger)width * 4;
    u8 *row = new u8[dstRowBytes];
    for (i32 y = 0; y < height; y++)
    {
        const u8 *srcRow = src + (NS::UInteger)y * (NS::UInteger)width * 3;
        for (i32 x = 0; x < width; x++)
        {
            u8 *dstPx = row + (NS::UInteger)x * 4;
            dstPx[0] = srcRow[(NS::UInteger)x * 3 + 0];
            dstPx[1] = srcRow[(NS::UInteger)x * 3 + 1];
            dstPx[2] = srcRow[(NS::UInteger)x * 3 + 2];
            dstPx[3] = 0xFF;
        }
        MTL::Region region = MTL::Region::Make2D((NS::UInteger)xoffset,
                                                  (NS::UInteger)(yoffset + y),
                                                  (NS::UInteger)width, 1);
        this->currentTexture->replaceRegion(region, 0, row, dstRowBytes);
    }
    delete[] row;
}

void MetalBackend::ReadPixels(i32 x, i32 y, i32 width, i32 height, const void *pixels)
{
    // M5: read a region of the framebuffer into a CPU buffer. Used for
    // screenshot/capture-to-texture in AnmManager (line 2087). The game
    // passes Y in GL bottom-origin convention (the call site already flips
    // it: `GAME_WINDOW_HEIGHT_REAL - ((top + height) * HEIGHT_RESOLUTION_SCALE)
    // - VIEWPORT_OFF_Y`). Metal's drawable texture is top-origin, so we flip
    // Y back to top-origin before reading.
    //
    // Strategy (per approved prep decision): end the current render pass,
    // commit the command buffer and wait for it to complete, then read the
    // drawable's texture via getBytes. SwapBuffers later presents the same
    // drawable — the pass will be re-opened by the next Draw or by
    // SwapBuffers' lazy BeginFrame. Reading mid-frame would require a
    // blit encoder and a shared staging texture; the end-pass-commit-wait
    // approach is simpler and matches the screenshot use case (called once
    // per capture, not per frame).
    if (pixels == nullptr || width <= 0 || height <= 0 || this->currentDrawable == nullptr)
    {
        return;
    }

    // End any open render pass — getBytes on the drawable texture requires
    // no encoder is writing to it.
    if (this->currentRenderEncoder != nullptr)
    {
        this->currentRenderEncoder->endEncoding();
        this->currentRenderEncoder = nullptr;
    }

    // Commit the pending command buffer (which may contain draws from
    // earlier in the frame) and wait for the GPU to finish before reading.
    // The drawable's texture is only valid for CPU read after the commands
    // writing to it have completed.
    MTL::CommandBuffer *cmdBuf = this->currentCommandBuffer;
    if (cmdBuf == nullptr)
    {
        // No frame was open — nothing to read.
        return;
    }

    // Use a blit encoder to copy the drawable texture into a Shared-storage
    // staging buffer we can map on the CPU. The drawable texture is
    // Private-storage (GPU-local); getBytes on a Private texture returns
    // undefined data. The staging buffer is the supported readback path.
    NS::UInteger bytesPerRow = (NS::UInteger)width * 4; // RGBA8
    NS::UInteger byteLength = bytesPerRow * (NS::UInteger)height;
    MTL::Buffer *staging = this->device->newBuffer(byteLength,
                                                    MTL::ResourceOptionCPUCacheModeDefault);
    if (staging == nullptr)
    {
        utils::DebugPrint2("MetalBackend: ReadPixels staging buffer alloc failed");
        return;
    }
    staging->setLabel(NS::String::string("th06 readpixels staging", NS::UTF8StringEncoding));

    MTL::BlitCommandEncoder *blit = cmdBuf->blitCommandEncoder();
    if (blit != nullptr)
    {
        blit->setLabel(NS::String::string("th06 readpixels blit", NS::UTF8StringEncoding));
        // Flip Y from GL bottom-origin to Metal top-origin. The game's Y
        // argument is measured from the bottom of the window; Metal's
        // texture origin is the top. The drawable's height is the window's
        // drawable height.
        int drawableH = 0;
        {
            int dw = 0;
            SDL_Metal_GetDrawableSize(this->window, &dw, &drawableH);
        }
        NS::UInteger metalY = (NS::UInteger)(drawableH - 1 - y - height + 1);
        MTL::Origin flippedOrigin((NS::UInteger)x, metalY, 0);
        MTL::Size srcSize((NS::UInteger)width, (NS::UInteger)height, 1);
        blit->copyFromTexture(this->currentDrawable->texture(),
                              0, 0, flippedOrigin, srcSize,
                              staging, 0, bytesPerRow, byteLength);
        blit->endEncoding();
    }

    cmdBuf->commit();
    cmdBuf->waitUntilCompleted();

    // The command buffer and drawable are autoreleased (+0); framePool's
    // drain in SwapBuffers handles them. Drop our references so the next
    // SwapBuffers doesn't double-commit.
    this->currentCommandBuffer = nullptr;

    // Copy + swizzle from the staging buffer (BGRA8, the drawable's format)
    // to the game's RGBA output buffer. The drawable texture is
    // PixelFormatBGRA8Unorm; getBytes/replaceRegion byte order matches the
    // format, so the staging buffer contains B,G,R,A per pixel.
    const u8 *src = (const u8 *)staging->contents();
    u8 *dst = (u8 *)pixels;
    for (i32 row = 0; row < height; row++)
    {
        const u8 *srcRow = src + (NS::UInteger)row * bytesPerRow;
        u8 *dstRow = dst + (NS::UInteger)row * bytesPerRow;
        for (i32 px = 0; px < width; px++)
        {
            u8 b = srcRow[(NS::UInteger)px * 4 + 0];
            u8 g = srcRow[(NS::UInteger)px * 4 + 1];
            u8 r = srcRow[(NS::UInteger)px * 4 + 2];
            u8 a = srcRow[(NS::UInteger)px * 4 + 3];
            dstRow[(NS::UInteger)px * 4 + 0] = r;
            dstRow[(NS::UInteger)px * 4 + 1] = g;
            dstRow[(NS::UInteger)px * 4 + 2] = b;
            dstRow[(NS::UInteger)px * 4 + 3] = a;
        }
    }

    staging->release();
}

void MetalBackend::Draw(PrimitiveType type, i32 start, i32 count)
{
    // M3/M5: build a PipelineKey from the recorded attribute state + current
    // blend mode, fetch (or create) the matching PSO, copy the vertex slice
    // into the persistent vertex buffer, snapshot the current uniforms into
    // the uniform ring, apply viewport + depth-stencil state, and issue a
    // drawPrimitives call. The frame's render pass is opened lazily by
    // BeginFrame if no encoder is active yet.
    if (this->currentRenderEncoder == nullptr)
    {
        this->BeginFrame();
        if (this->currentRenderEncoder == nullptr)
        {
            return;
        }
    }

    // Derive the layout portion of the key. POSITION is always present and
    // is the base of the vertex array; the per-attribute offsets come from
    // the byte difference between each attribute's recorded ptr and
    // POSITION's ptr. The stride is taken from POSITION (all three
    // SetAttributePointer calls for one draw use the same stride).
    VertexAttribState &pos = this->attribs[VERTEX_ARRAY_POSITION];
    if (pos.ptr == nullptr || pos.stride == 0)
    {
        // No position attribute bound — nothing to draw. Defensive; the game
        // always sets POSITION before Draw.
        return;
    }

    PipelineKey key;
    key.stride = (NS::UInteger)pos.stride;
    key.positionOffset = 0;
    // When SetAttributePointer wasn't called for TEX_COORD or DIFFUSE before
    // this Draw, the recorded ptr is nullptr. The vertex descriptor still
    // declares those attributes as [[stage_in]], so the vertex fetch hardware
    // reads from whatever offset we set — computing `nullptr - pos.ptr` wraps
    // to a huge negative value and produces garbage fetches. Point the unused
    // attribute at offset 0 (the position data, always valid within the
    // copied slice). The shader's useTexCoords/useDiffuse flags gate the
    // values at the fragment stage, so reading garbage here is harmless.
    const void *texPtr = this->attribs[VERTEX_ARRAY_TEX_COORD].ptr;
    const void *difPtr = this->attribs[VERTEX_ARRAY_DIFFUSE].ptr;
    key.texCoordOffset = texPtr ? (NS::UInteger)((u8 *)texPtr - (u8 *)pos.ptr) : 0;
    key.diffuseOffset = difPtr ? (NS::UInteger)((u8 *)difPtr - (u8 *)pos.ptr) : 0;
    // M5: blend mode in the PSO key. If blend is disabled (Enable was never
    // called), use -1 so the PSO is built with blendingEnabled=false. The
    // game toggles SetBlendMode per sprite group; each unique (layout, blend)
    // tuple gets its own cached PSO.
    key.blendMode = this->blendEnabled ? this->currentBlendMode : -1;

    MTL::RenderPipelineState *pso = this->GetPipeline(key);
    if (pso == nullptr)
    {
        return;
    }
    this->currentRenderEncoder->setRenderPipelineState(pso);

    // M5: apply viewport + depth range. No-op if viewportDirty is false and
    // the viewport hasn't changed. Flips Y from GL bottom-origin to Metal
    // top-origin.
    if (this->viewportDirty)
    {
        this->ApplyViewport();
        this->viewportDirty = false;
    }

    // M5: look up the depth-stencil state for the current
    // (depthWrite, depthCompare) tuple. When depth test is disabled, use
    // CompareFunctionAlways + writeEnabled=false (equivalent to GL disabling
    // the depth test — no compare, no write). When enabled, map the game's
    // DepthFunc to MTL::CompareFunction.
    DepthStencilKey dsKey;
    if (this->depthTestEnabled)
    {
        dsKey.depthWriteEnabled = this->depthMaskEnabled;
        dsKey.depthCompare = (this->depthFunc == DEPTH_FUNC_ALWAYS)
                                 ? (i32)MTL::CompareFunctionAlways
                                 : (i32)MTL::CompareFunctionLessEqual;
    }
    else
    {
        dsKey.depthWriteEnabled = false;
        dsKey.depthCompare = (i32)MTL::CompareFunctionAlways;
    }
    MTL::DepthStencilState *dsState = this->GetDepthStencilState(dsKey);
    if (dsState != nullptr)
    {
        this->currentRenderEncoder->setDepthStencilState(dsState);
    }

    // Copy the CPU vertex slice into the persistent vertex buffer and bind
    // it at buffer index 1 (matches the MSL `stage_in` vertex descriptor).
    NS::UInteger vertexOffset = this->CopyVertexData(key, start, count);
    this->currentRenderEncoder->setVertexBuffer(this->vertexBuffer, vertexOffset,
                                                  kVertexBufferIndex);

    // Snapshot the current uniforms into the ring and bind at buffer index 0
    // for both vertex and fragment stages. Each Draw gets its own slice so
    // per-sprite matrix updates don't desync.
    NS::UInteger uniformOffset = this->FlushUniforms();
    this->currentRenderEncoder->setVertexBuffer(this->uniformBuffer, uniformOffset, 0);
    this->currentRenderEncoder->setFragmentBuffer(this->uniformBuffer, uniformOffset, 0);

    // M4: bind the active texture + persistent linear sampler at fragment
    // stage texture(0)/sampler(0). Matches the MSL `ff_fragment` signature.
    // If no texture is bound (currentTexture == nullptr), the shader's
    // useTexCoords=0 path falls back to the diffuse color and texture(0) is
    // unbound — Metal validation permits unbound textures as long as the
    // shader doesn't sample them, which the useTexCoords gate enforces.
    if (this->currentTexture != nullptr)
    {
        this->currentRenderEncoder->setFragmentTexture(this->currentTexture, 0);
    }
    if (this->samplerState != nullptr)
    {
        this->currentRenderEncoder->setFragmentSamplerState(this->samplerState, 0);
    }

    // Map the engine primitive type to MTL::PrimitiveType. The game only uses
    // triangle strip and triangles (see GfxInterface.hpp).
    MTL::PrimitiveType mtlPrim;
    switch (type)
    {
    case PRIM_TRIANGLE_STRIP:
        mtlPrim = MTL::PrimitiveTypeTriangleStrip;
        break;
    case PRIM_TRIANGLES:
        mtlPrim = MTL::PrimitiveTypeTriangle;
        break;
    default:
        return;
    }

    this->currentRenderEncoder->drawPrimitives(mtlPrim, (NS::UInteger)0, (NS::UInteger)count);
}

// M5: apply the cached viewport + depth range to the current render encoder.
// The game stores viewport Y in GL bottom-origin convention (ZunViewport::Set
// flips Y before calling SetViewport). Metal's viewport origin is top-left,
// so we flip Y = (drawableHeight - y - height). A viewport of {0,0,0,0}
// means "use the full drawable" — we query SDL for the drawable size and use
// it directly. Depth range maps to Metal's depth clip plane (near, far).
void MetalBackend::ApplyViewport()
{
    if (this->currentRenderEncoder == nullptr)
    {
        return;
    }

    int drawableW = 0, drawableH = 0;
    SDL_Metal_GetDrawableSize(this->window, &drawableW, &drawableH);

    MTL::Viewport vp;
    if (this->viewport[2] > 0 && this->viewport[3] > 0)
    {
        // Flip Y from GL bottom-origin to Metal top-origin.
        vp.originX = (double)this->viewport[0];
        vp.originY = (double)(drawableH - this->viewport[1] - this->viewport[3]);
        vp.width   = (double)this->viewport[2];
        vp.height  = (double)this->viewport[3];
    }
    else
    {
        // No viewport set — use the full drawable.
        vp.originX = 0.0;
        vp.originY = 0.0;
        vp.width   = (double)drawableW;
        vp.height  = (double)drawableH;
    }
    vp.znear = (double)this->depthRange[0];
    vp.zfar  = (double)this->depthRange[1];
    this->currentRenderEncoder->setViewport(vp);
}

// M3: open the per-frame render pass. Acquires the drawable, allocates the
// depth texture if needed, bakes pendingClearBits into the load actions,
// creates the encoder, and binds the depth-stencil state. Draw calls happen
// between BeginFrame and SwapBuffers; SwapBuffers ends encoding and presents.
//
// Idempotent within a frame: if called when an encoder is already open, it
// returns immediately. This makes it safe to call from Clear before any draw,
// or from the first Draw if Clear wasn't called — the game's frame pattern
// is Clear(color|depth) at frame start, but some early-init paths draw
// before the first Clear.
void MetalBackend::BeginFrame()
{
    if (this->currentRenderEncoder != nullptr)
    {
        return;
    }

    // The frame pool lives for the entire frame — drained in SwapBuffers
    // after endEncoding. The encoder returned by renderCommandEncoder() is
    // autoreleased (+0); if we drained a per-function pool here, the encoder
    // would be released before endEncoding, triggering a validation
    // assertion. Draining early was the M3 first-pass bug.
    this->framePool = NS::AutoreleasePool::alloc()->init();

    // Reset the per-frame ring offsets. The previous frame's GPU work has
    // completed by now — its command buffer was committed in SwapBuffers and
    // the next drawable acquisition below blocks until a drawable is free.
    this->frameVertexOffset = 0;
    this->frameUniformOffset = 0;

    // Keep the layer's drawableSize in sync with the window. The game window
    // is fixed-size, but this is cheap and handles fullscreen transitions.
    int w = 0, h = 0;
    SDL_Metal_GetDrawableSize(this->window, &w, &h);
    if (w > 0 && h > 0)
    {
        this->layer->setDrawableSize(CGSizeMake(w, h));
    }

    // Acquire the drawable for this frame. nextDrawable blocks on the CPU
    // until a drawable is available from the pool (max 2 in flight).
    this->currentDrawable = this->layer->nextDrawable();
    if (this->currentDrawable == nullptr)
    {
        utils::DebugPrint2("MetalBackend: nextDrawable returned null");
        this->pendingClearBits = 0;
        this->framePool->drain();
        this->framePool = nullptr;
        return;
    }

    this->currentCommandBuffer = this->commandQueue->commandBuffer();
    this->currentCommandBuffer->setLabel(NS::String::string("th06 frame", NS::UTF8StringEncoding));

    // Reuse the persistent depth texture across frames; (re)allocate if the
    // drawable size has changed.
    this->EnsureDepthTexture((NS::UInteger)w, (NS::UInteger)h);

    MTL::RenderPassDescriptor *desc = MTL::RenderPassDescriptor::renderPassDescriptor();
    desc->setRenderTargetWidth((NS::UInteger)w);
    desc->setRenderTargetHeight((NS::UInteger)h);

    // Color attachment 0 = the drawable's texture. Load=Clear bakes the clear
    // value into the pass; Store=Store writes the result back for presentation.
    // If no color clear was requested this frame, Load=Load preserves prior
    // contents.
    MTL::RenderPassColorAttachmentDescriptor *colorAtt = desc->colorAttachments()->object(0);
    colorAtt->setTexture(this->currentDrawable->texture());
    if (this->pendingClearBits & CLEAR_COLOR_BUFFER)
    {
        colorAtt->setLoadAction(MTL::LoadActionClear);
        colorAtt->setClearColor(MTL::ClearColor::Make(this->clearColor[0], this->clearColor[1],
                                                        this->clearColor[2], this->clearColor[3]));
    }
    else
    {
        colorAtt->setLoadAction(MTL::LoadActionLoad);
    }
    colorAtt->setStoreAction(MTL::StoreActionStore);

    // Depth attachment = persistent depth texture. Even if the game didn't
    // request a depth clear this frame, the attachment must be present for
    // the depth-stencil state to take effect. Load=Clear when
    // CLEAR_DEPTH_BUFFER was requested, else Load=Load. Store=DontCare — we
    // never read back the depth texture, and discarding at pass end saves
    // bandwidth.
    if (this->depthTexture != nullptr)
    {
        MTL::RenderPassDepthAttachmentDescriptor *depthAtt = desc->depthAttachment();
        depthAtt->setTexture(this->depthTexture);
        if (this->pendingClearBits & CLEAR_DEPTH_BUFFER)
        {
            depthAtt->setLoadAction(MTL::LoadActionClear);
            depthAtt->setClearDepth(this->clearDepth);
        }
        else
        {
            depthAtt->setLoadAction(MTL::LoadActionLoad);
        }
        depthAtt->setStoreAction(MTL::StoreActionDontCare);
    }

    // renderCommandEncoder() returns an autoreleased (+0) object — do NOT
    // release() it; framePool's drain in SwapBuffers handles it. The encoder
    // is held as a raw pointer across draws until SwapBuffers ends encoding.
    this->currentRenderEncoder = this->currentCommandBuffer->renderCommandEncoder(desc);
    this->currentRenderEncoder->setLabel(NS::String::string("th06 main pass", NS::UTF8StringEncoding));

    // M5: depth-stencil state is now bound per-Draw in Draw() because it
    // varies with SetDepthMask/SetDepthFunc/Enable(CAPS_DEPTH_TEST) state.
    // BeginFrame no longer binds a fixed default state.

    // pendingClearBits was consumed by the load actions above. Reset so
    // mid-frame Clears after the pass is open don't carry over to next
    // frame's load actions.
    this->pendingClearBits = 0;

    // desc is autoreleased (+0); framePool's drain releases it.
    desc = nullptr;
}

void MetalBackend::SwapBuffers()
{
    // M3: end encoding and present. The render pass was opened in BeginFrame
    // (called lazily from the first Clear or Draw of the frame). If no draws
    // happened this frame (e.g. a startup path), BeginFrame is called here
    // so the clear still applies and a valid frame is presented.
    if (this->currentRenderEncoder == nullptr)
    {
        this->BeginFrame();
    }

    if (this->currentRenderEncoder != nullptr)
    {
        this->currentRenderEncoder->endEncoding();
        this->currentRenderEncoder = nullptr;
    }

    if (this->currentCommandBuffer != nullptr && this->currentDrawable != nullptr)
    {
        this->currentCommandBuffer->presentDrawable(this->currentDrawable);
        this->currentCommandBuffer->commit();
    }

    // Release per-frame state. commandBuffer() and nextDrawable() both return
    // autoreleased (+0) objects — do NOT release() them; framePool's drain
    // handles them.
    this->currentCommandBuffer = nullptr;
    this->currentDrawable = nullptr;

    // pendingClearBits was consumed by BeginFrame's load actions. Defensive
    // reset in case BeginFrame was skipped (e.g. nextDrawable failed).
    this->pendingClearBits = 0;

    // Drain the frame pool now that the encoder has been ended. This
    // releases the autoreleased encoder, command buffer, drawable, and
    // render pass descriptor captured during BeginFrame.
    if (this->framePool != nullptr)
    {
        this->framePool->drain();
        this->framePool = nullptr;
    }
}
