#include "MetalBackend.hpp"

#include "GameWindow.hpp"
#include "Supervisor.hpp"
#include "i18n.hpp"
#include "utils.hpp"

// metal-cpp single-header includes NS::Object, MTL::Device, CA::MetalLayer,
// and MTL4::CommandQueue. The single header pulls Foundation + Metal +
// QuartzCore together; this is the recommended integration approach.
//
// The *_PRIVATE_IMPLEMENTATION defines must be set before including the
// single header — they expand the inline objc_msgSend shims into real
// symbols in this TU. Define them in exactly one translation unit.
#define NS_PRIVATE_IMPLEMENTATION
#define MTL_PRIVATE_IMPLEMENTATION
#define CA_PRIVATE_IMPLEMENTATION
#include "thirdparty/metal-cpp/SingleHeader/Metal.hpp"

#include <SDL2/SDL.h>
#include <SDL2/SDL_syswm.h>

#include <cstdio>
#include <cstring>

// ============================================================================
// M2: MSL shaders — translation of src/graphics/ff.vert + ff.frag.
// Embedded as C++ string literals and compiled at runtime via
// device->newLibraryWithSource(). This mirrors the WebGL backend, which
// embeds the GLSL via autogenerated/Embeds.hpp and compiles it at startup.
//
// Binding model:
//   buffer(0) — MetalUniforms (vertex + fragment stage)
//   texture(0) — bound texture (fragment stage; M4 populates)
//   sampler(0) — bound sampler (fragment stage; M4 populates)
//
// Vertex attributes (set in the vertex descriptor built in Init()):
//   attribute(0) — position  float3
//   attribute(1) — texCoords float2
//   attribute(2) — diffuse   uchar4 normalized → float4 in shader
//
// The frag shader's NO_VERTEX_BUFFER / NO_FOG / USE_FRAG_DEPTH preprocessor
// branches from the GLSL are translated to the default path (envDiffuse used
// as fragArg2, fog applied, alpha-test via discard). EoSD always uses these
// defaults; the GL backend's omittedUniforms set excludes fog only when the
// context lacks it. The Metal path always has fog available.
// ============================================================================
static const char *kMSLVertexSource = R"MSL(
#include <metal_stdlib>
using namespace metal;

// Keep this layout in sync with MetalUniforms in MetalBackend.hpp.
// std140-style explicit packing; metal-cpp's MTLBuffer contents are raw bytes.
struct Uniforms
{
    float4x4 modelviewMatrix;
    float4x4 projectionMatrix;
    float4x4 textureMatrix;
    float4   envDiffuse;
    float4   fogColor;
    int      useTexCoords;
    int      useDiffuse;
    int      colorOp;
    float    fogNear;
    float    fogFar;
};

struct VertexIn
{
    float3 position  [[attribute(0)]];
    float2 texCoords [[attribute(1)]];
    float4 diffuse   [[attribute(2)]];
};

struct VertexOut
{
    float4 position     [[position]];
    float2 texCoords;
    float4 diffuse;
    float  viewZ;
};

vertex VertexOut ff_vertex(VertexIn in [[stage_in]],
                           constant Uniforms &u [[buffer(0)]])
{
    VertexOut out;
    out.texCoords = (u.textureMatrix * float4(in.texCoords, 1.0, 1.0)).xy;
    out.diffuse   = in.diffuse;
    float4 viewCoordinates = u.modelviewMatrix * float4(in.position, 1.0);
    out.viewZ     = viewCoordinates.z;
    out.position  = u.projectionMatrix * viewCoordinates;
    return out;
}
)MSL";

static const char *kMSLFragmentSource = R"MSL(
#include <metal_stdlib>
using namespace metal;

struct Uniforms
{
    float4x4 modelviewMatrix;
    float4x4 projectionMatrix;
    float4x4 textureMatrix;
    float4   envDiffuse;
    float4   fogColor;
    int      useTexCoords;
    int      useDiffuse;
    int      colorOp;
    float    fogNear;
    float    fogFar;
};

struct VertexOut
{
    float4 position     [[position]];
    float2 texCoords;
    float4 diffuse;
    float  viewZ;
};

#define OP_MODULATE 0
#define OP_ADD      1
#define OP_REPLACE  2

constant float alphaThreshold = 4.0 / 255.0;

fragment float4 ff_fragment(VertexOut in     [[stage_in]],
                            constant Uniforms &u [[buffer(0)]],
                            texture2d<float> tex [[texture(0)]],
                            sampler smp [[sampler(0)]])
{
    float4 fragColor = float4(0.0, 0.0, 0.0, 0.0);
    float4 fragArg1;
    float4 fragArg2;

    if (u.useTexCoords != 0)
    {
        fragArg1 = tex.sample(smp, in.texCoords);
    }
    else
    {
        fragArg1 = in.diffuse;
    }
    fragArg2 = u.envDiffuse;

    if (u.colorOp == OP_MODULATE)
    {
        fragColor = fragArg1 * fragArg2;
    }
    else if (u.colorOp == OP_ADD)
    {
        // EoSD: add applies to RGB only; alpha still modulates.
        fragColor.rgb = min(fragArg1.rgb + fragArg2.rgb, float3(1.0, 1.0, 1.0));
        fragColor.a   = fragArg1.a * fragArg2.a;
    }
    else // OP_REPLACE
    {
        fragColor = fragArg1;
    }

    // Fog. View-space depth from the vertex shader.
    float fogCoefficient = (u.fogFar - in.viewZ) / (u.fogFar - u.fogNear);
    fogCoefficient = clamp(fogCoefficient, 0.0, 1.0);
    fragColor.rgb = mix(u.fogColor.rgb, fragColor.rgb, fogCoefficient);

    if (fragColor.a < alphaThreshold)
    {
        discard_fragment();
    }
    return fragColor;
}
)MSL";

GfxInterface *MetalBackend::Create()
{
    MetalBackend *interface = new MetalBackend;

    SDL_Init(SDL_INIT_VIDEO);

    u32 flags = SDL_WINDOW_METAL | SDL_WINDOW_SHOWN;
    i32 height = GAME_WINDOW_HEIGHT_REAL;
    i32 width = GAME_WINDOW_WIDTH_REAL;
    i32 x = SDL_WINDOWPOS_UNDEFINED;
    i32 y = SDL_WINDOWPOS_UNDEFINED;

    if (g_Supervisor.cfg.windowed == 0)
    {
        flags |= SDL_WINDOW_FULLSCREEN;
    }

    SDL_Window *window = SDL_CreateWindow(TH_WINDOW_TITLE, x, y, width, height, flags);
    interface->window = window;
    if (window == NULL)
    {
        utils::DebugPrint2("MetalBackend: SDL_CreateWindow failed: %s", SDL_GetError());
        delete interface;
        return nullptr;
    }

    if (!interface->Init())
    {
        delete interface;
        return nullptr;
    }

    utils::DebugPrint2("MetalBackend: using MTL::Device + MTL::CommandQueue");
    return interface;
}

bool MetalBackend::Init()
{
    NS::AutoreleasePool *pool = NS::AutoreleasePool::alloc()->init();

    // SDL_Metal_CreateView returns an opaque SDL_MetalView (a CAMetalLayer-backed
    // NSView on macOS). SDL_Metal_GetLayer unwraps it to the raw CAMetalLayer*.
    this->metalView = SDL_Metal_CreateView(this->window);
    if (this->metalView == NULL)
    {
        utils::DebugPrint2("MetalBackend: SDL_Metal_CreateView failed: %s", SDL_GetError());
        pool->drain();
        return false;
    }

    this->layer = static_cast<CA::MetalLayer *>(SDL_Metal_GetLayer(this->metalView));
    if (this->layer == nullptr)
    {
        utils::DebugPrint2("MetalBackend: SDL_Metal_GetLayer returned null");
        pool->drain();
        return false;
    }

    // Create the system default device and bind it to the layer. The layer's
    // device must match the device used to render its drawables.
    this->device = MTL::CreateSystemDefaultDevice();
    if (this->device == nullptr)
    {
        utils::DebugPrint2("MetalBackend: MTL::CreateSystemDefaultDevice returned null (Metal not available)");
        pool->drain();
        return false;
    }
    this->layer->setDevice(this->device);

    // Configure the CAMetalLayer for presentation. BGRA8Unorm matches the
    // pipeline color attachment format we'll create in M2. framebufferOnly=YES
    // enables GPU compression and is fine until ReadPixels (M5) needs readback.
    // displaySyncEnabled=YES caps presentation to the display refresh rate.
    this->layer->setPixelFormat(MTL::PixelFormatBGRA8Unorm);
    this->layer->setMaximumDrawableCount(2);
    this->layer->setFramebufferOnly(true);
    this->layer->setDisplaySyncEnabled(true);
    // Note: metal-cpp's CA::MetalLayer binding does not expose setOpaque in
    // this version. The layer is opaque in practice for a fullscreen game;
    // direct-to-display eligibility is not needed for M1's clear-screen check.
    // drawableSize is set per-frame in SwapBuffers() from the window size, so
    // resize is handled without a separate windowDidResize: hook (the game
    // window is fixed at GAME_WINDOW_*_REAL).

    // Command queue. The goal doc targeted MTL4::CommandQueue, but MTL4 requires
    // macOS 26 (Tahoe); this dev machine is macOS 15 (Sequoia), where the
    // MTL4 selector throws at runtime. Per user direction, the port uses the
    // MTL (Metal 3) command queue, which runs on every supported macOS.
    // Migrating to MTL4 on a Tahoe target is a mechanical swap.
    this->commandQueue = this->device->newCommandQueue();
    if (this->commandQueue == nullptr)
    {
        utils::DebugPrint2("MetalBackend: newCommandQueue returned null");
        pool->drain();
        return false;
    }

    // M2: build the render pipeline, depth-stencil state, uniform buffer,
    // and persistent depth texture. Failure of any sub-step is fatal — the
    // backend can't render without a pipeline.
    if (!this->InitPipeline())
    {
        pool->drain();
        return false;
    }

    // Initialize uniforms to identity matrices + sensible defaults. The WebGL
    // backend does the same in its Init(): identity modelview/projection/
    // texture, fogFar=1. envDiffuse/fogColor default to opaque black via the
    // zero-init here; the game sets real values before drawing.
    this->uniforms.modelviewMatrix.Identity();
    this->uniforms.projectionMatrix.Identity();
    this->uniforms.textureMatrix.Identity();
    this->uniforms.envDiffuse = ZunVec4(0.0f, 0.0f, 0.0f, 1.0f);
    this->uniforms.fogColor = ZunVec4(0.0f, 0.0f, 0.0f, 1.0f);
    this->uniforms.useTexCoords = 0;
    this->uniforms.useDiffuse = 0;
    this->uniforms.colorOp = COLOR_OP_MODULATE;
    this->uniforms.fogNear = 0.0f;
    this->uniforms.fogFar = 1.0f;

    // Flush the initial uniform values into the GPU buffer so the first frame
    // has sane state even if the game doesn't set everything before drawing.
    this->FlushUniforms();

    pool->drain();
    return true;
}

// M2: build the MSL library, vertex/fragment functions, render pipeline state,
// depth-stencil state, uniform buffer, and the persistent depth texture.
//
// All metal-cpp factory calls below follow the autorelease rule documented in
// the team memory: methods whose name contains new/alloc/copy/Create return
// owned (+1) objects we must release(); others return autoreleased (+0)
// objects we hold as raw pointers within this autorelease pool scope.
bool MetalBackend::InitPipeline()
{
    NS::AutoreleasePool *pool = NS::AutoreleasePool::alloc()->init();
    bool ok = false;

    MTL::VertexDescriptor *vertexDescriptor = nullptr;
    MTL::RenderPipelineDescriptor *pipelineDesc = nullptr;
    NS::Error *pipelineError = nullptr;
    NS::Error *fragCompileError = nullptr;
    MTL::Library *fragLib = nullptr;

    // Compile the embedded MSL sources. Each shader is compiled as its own
    // library — they declare the same Uniforms/VertexOut structs, so
    // concatenating would trigger redefinition errors. newLibrary returns
    // owned (+1) Libraries — released in Exit().
    NS::Error *compileError = nullptr;
    MTL::CompileOptions *options = MTL::CompileOptions::alloc()->init();
    NS::String *vertexSrc = NS::String::string(kMSLVertexSource, NS::UTF8StringEncoding);
    NS::String *fragSrc = NS::String::string(kMSLFragmentSource, NS::UTF8StringEncoding);
    MTL::Library *vertLib = this->device->newLibrary(vertexSrc, options, &compileError);
    if (vertLib == nullptr)
    {
        if (compileError != nullptr)
        {
            utils::DebugPrint2("MetalBackend: vertex MSL compile failed: %s",
                                compileError->localizedDescription()->utf8String());
        }
        else
        {
            utils::DebugPrint2("MetalBackend: vertex MSL compile failed (no error)");
        }
        options->release();
        goto cleanup;
    }
    vertLib->setLabel(NS::String::string("th06 ff vertex", NS::UTF8StringEncoding));

    // Reuse the same CompileOptions for the fragment library.
    fragLib = this->device->newLibrary(fragSrc, options, &fragCompileError);
    options->release();
    if (fragLib == nullptr)
    {
        if (fragCompileError != nullptr)
        {
            utils::DebugPrint2("MetalBackend: fragment MSL compile failed: %s",
                                fragCompileError->localizedDescription()->utf8String());
        }
        else
        {
            utils::DebugPrint2("MetalBackend: fragment MSL compile failed (no error)");
        }
        vertLib->release();
        goto cleanup;
    }
    fragLib->setLabel(NS::String::string("th06 ff fragment", NS::UTF8StringEncoding));

    // Keep shaderLibrary pointing at the vertex library for the label/debug
    // grouping; the fragment library is held only long enough to look up the
    // function below. Both are released in cleanup.
    this->shaderLibrary = vertLib;
    this->shaderLibrary->setLabel(NS::String::string("th06 ff shaders", NS::UTF8StringEncoding));

    // Library::newFunction(name) returns an owned (+1) Function.
    this->vertexFunction = vertLib->newFunction(
        NS::String::string("ff_vertex", NS::UTF8StringEncoding));
    this->fragmentFunction = fragLib->newFunction(
        NS::String::string("ff_fragment", NS::UTF8StringEncoding));
    fragLib->release();
    if (this->vertexFunction == nullptr || this->fragmentFunction == nullptr)
    {
        utils::DebugPrint2("MetalBackend: function lookup failed");
        goto cleanup;
    }

    // Vertex descriptor — matches VertexIn in the MSL and the vertex format
    // documented in the goal doc (position float3, texCoords float2, diffuse
    // unorm4). M3 will wire SetAttributePointer to feed attributes 0/1/2.
    // alloc()->init() → owned (+1); released in cleanup below.
    vertexDescriptor = MTL::VertexDescriptor::alloc()->init();
    vertexDescriptor->attributes()->object(0)->setFormat(MTL::VertexFormatFloat3);
    vertexDescriptor->attributes()->object(0)->setBufferIndex(0);
    vertexDescriptor->attributes()->object(0)->setOffset(0);
    vertexDescriptor->attributes()->object(1)->setFormat(MTL::VertexFormatFloat2);
    vertexDescriptor->attributes()->object(1)->setBufferIndex(0);
    // HARDCODED: offset 12 = sizeof(float3). M3 will compute from the vertex
    // stride/layout recorded by SetAttributePointer.
    vertexDescriptor->attributes()->object(1)->setOffset(12);
    vertexDescriptor->attributes()->object(2)->setFormat(MTL::VertexFormatUChar4Normalized);
    vertexDescriptor->attributes()->object(2)->setBufferIndex(0);
    // HARDCODED: offset 20 = sizeof(float3) + sizeof(float2). M3 fix.
    vertexDescriptor->attributes()->object(2)->setOffset(20);
    // HARDCODED: stride 24 = sizeof(float3)+sizeof(float2)+sizeof(uint32_t).
    // M3 will set this from SetAttributePointer's stride argument.
    vertexDescriptor->layouts()->object(0)->setStride(24);

    // Render pipeline descriptor. alloc()->init() → owned (+1); released in
    // cleanup below.
    pipelineDesc = MTL::RenderPipelineDescriptor::alloc()->init();
    pipelineDesc->setVertexFunction(this->vertexFunction);
    pipelineDesc->setFragmentFunction(this->fragmentFunction);
    pipelineDesc->setVertexDescriptor(vertexDescriptor);
    // Color attachment 0 = the drawable's BGRA8Unorm (set on the layer in Init()).
    pipelineDesc->colorAttachments()->object(0)->setPixelFormat(MTL::PixelFormatBGRA8Unorm);
    // Default blend off — M5 will configure blend from SetBlendMode.
    pipelineDesc->setDepthAttachmentPixelFormat(MTL::PixelFormatDepth32Float);
    // No stencil — EoSD doesn't use stencil.
    pipelineDesc->setStencilAttachmentPixelFormat(MTL::PixelFormatInvalid);
    pipelineDesc->setLabel(NS::String::string("th06 ff pipeline", NS::UTF8StringEncoding));

    // newRenderPipelineState returns owned (+1) — released in Exit().
    this->pipelineState = this->device->newRenderPipelineState(pipelineDesc, &pipelineError);
    if (this->pipelineState == nullptr)
    {
        if (pipelineError != nullptr)
        {
            utils::DebugPrint2("MetalBackend: newRenderPipelineState failed: %s",
                                pipelineError->localizedDescription()->utf8String());
        }
        else
        {
            utils::DebugPrint2("MetalBackend: newRenderPipelineState failed (no error)");
        }
        goto cleanup;
    }

    // Depth-stencil state. EoSD uses LEQUAL depth test with depth write
    // enabled (the game calls SetDepthMask(true) and SetDepthFunc(LEQUAL)
    // during init). M5 will rebuild this when SetDepthMask/SetDepthFunc are
    // called; M2 bakes the default.
    {
        MTL::DepthStencilDescriptor *depthDesc = MTL::DepthStencilDescriptor::alloc()->init();
        depthDesc->setDepthCompareFunction(MTL::CompareFunctionLessEqual);
        depthDesc->setDepthWriteEnabled(true);
        depthDesc->setLabel(NS::String::string("th06 depth (LEQUAL, write)", NS::UTF8StringEncoding));
        this->depthStencilState = this->device->newDepthStencilState(depthDesc);
        depthDesc->release();
    }
    if (this->depthStencilState == nullptr)
    {
        utils::DebugPrint2("MetalBackend: newDepthStencilState failed");
        goto cleanup;
    }

    // Uniform buffer. Shared storage mode = CPU-visible, GPU-readable, no
    // shared-managed blit needed on unified-memory Apple Silicon. Size is
    // sizeof(MetalUniforms); the layout in the MSL shader matches via the
    // explicit struct definition. newBuffer returns owned (+1) — released
    // in Exit().
    this->uniformBuffer = this->device->newBuffer(sizeof(MetalUniforms),
                                                    MTL::ResourceOptionCPUCacheModeDefault);
    if (this->uniformBuffer == nullptr)
    {
        utils::DebugPrint2("MetalBackend: uniform newBuffer failed");
        goto cleanup;
    }
    this->uniformBuffer->setLabel(NS::String::string("th06 uniforms", NS::UTF8StringEncoding));

    // Persistent depth texture — allocated lazily in EnsureDepthTexture on
    // the first frame, when the drawable size is known. M1 allocated a
    // throwaway per-frame; M2 reuses one across frames and only reallocates
    // on resize.
    this->depthTexture = nullptr;
    this->depthTextureWidth = 0;
    this->depthTextureHeight = 0;

    ok = true;

cleanup:
    if (vertexDescriptor != nullptr) vertexDescriptor->release();
    if (pipelineDesc != nullptr) pipelineDesc->release();
    pool->drain();
    return ok;
}

// Copy the CPU-side `uniforms` struct into the GPU-visible uniform buffer.
// Called at frame open (SwapBuffers) and once at Init() to seed the buffer.
// The buffer is Shared storage mode — contents() returns a CPU pointer we
// can memcpy into directly. No encoder/blit needed.
void MetalBackend::FlushUniforms()
{
    if (this->uniformBuffer == nullptr)
    {
        return;
    }
    void *gpu = this->uniformBuffer->contents();
    if (gpu != nullptr)
    {
        std::memcpy(gpu, &this->uniforms, sizeof(MetalUniforms));
    }
}

// (Re)allocate the persistent depth texture if the drawable size has changed.
// Called from SwapBuffers before opening the render pass. The depth texture
// is Private storage (GPU-local only) — it's a render target, never mapped.
void MetalBackend::EnsureDepthTexture(NS::UInteger width, NS::UInteger height)
{
    if (this->depthTexture != nullptr &&
        this->depthTextureWidth == width &&
        this->depthTextureHeight == height)
    {
        return;
    }

    if (this->depthTexture != nullptr)
    {
        this->depthTexture->release();
        this->depthTexture = nullptr;
    }

    if (width == 0 || height == 0)
    {
        return;
    }

    MTL::TextureDescriptor *desc = MTL::TextureDescriptor::alloc()->init();
    desc->setTextureType(MTL::TextureType2D);
    desc->setPixelFormat(MTL::PixelFormatDepth32Float);
    desc->setWidth(width);
    desc->setHeight(height);
    desc->setStorageMode(MTL::StorageModePrivate);
    desc->setUsage(MTL::TextureUsageRenderTarget);
    this->depthTexture = this->device->newTexture(desc);
    if (this->depthTexture != nullptr)
    {
        this->depthTexture->setLabel(NS::String::string("th06 depth", NS::UTF8StringEncoding));
        this->depthTextureWidth = width;
        this->depthTextureHeight = height;
    }
    else
    {
        utils::DebugPrint2("MetalBackend: depth newTexture failed (%lux%lu)",
                            (unsigned long)width, (unsigned long)height);
        this->depthTextureWidth = 0;
        this->depthTextureHeight = 0;
    }
    desc->release();
}

void MetalBackend::Exit()
{
    // metal-cpp objects are reference-counted via NS::Object; release() drops
    // our reference. The autorelease pool isn't required for release() itself
    // but keeps any transient objects created during teardown clean.
    NS::AutoreleasePool *pool = NS::AutoreleasePool::alloc()->init();

    // Tear down any in-flight frame state first — if Exit() is called mid-frame
    // (e.g. on error), the encoder/command buffer/drawable must be dropped
    // before the device and command queue go away. These are autoreleased (+0)
    // objects captured during the frame; do NOT release() them — the pool
    // drain below handles it. Just end any open encoding and clear the slots.
    if (this->currentRenderEncoder != nullptr)
    {
        this->currentRenderEncoder->endEncoding();
        this->currentRenderEncoder = nullptr;
    }
    this->currentCommandBuffer = nullptr;
    this->currentDrawable = nullptr;

    // M2 resources — all owned (+1) from new*/alloc()->init()/Create in
    // InitPipeline. Release in reverse-of-creation order. Uniform buffer,
    // depth texture, depth-stencil, pipeline, functions, library.
    if (this->uniformBuffer != nullptr)
    {
        this->uniformBuffer->release();
        this->uniformBuffer = nullptr;
    }
    if (this->depthTexture != nullptr)
    {
        this->depthTexture->release();
        this->depthTexture = nullptr;
        this->depthTextureWidth = 0;
        this->depthTextureHeight = 0;
    }
    if (this->depthStencilState != nullptr)
    {
        this->depthStencilState->release();
        this->depthStencilState = nullptr;
    }
    if (this->pipelineState != nullptr)
    {
        this->pipelineState->release();
        this->pipelineState = nullptr;
    }
    if (this->fragmentFunction != nullptr)
    {
        this->fragmentFunction->release();
        this->fragmentFunction = nullptr;
    }
    if (this->vertexFunction != nullptr)
    {
        this->vertexFunction->release();
        this->vertexFunction = nullptr;
    }
    if (this->shaderLibrary != nullptr)
    {
        this->shaderLibrary->release();
        this->shaderLibrary = nullptr;
    }

    if (this->commandQueue != nullptr)
    {
        this->commandQueue->release();
        this->commandQueue = nullptr;
    }
    if (this->device != nullptr)
    {
        this->device->release();
        this->device = nullptr;
    }
    // layer is owned by the NSView backing metalView; do not release it.
    this->layer = nullptr;

    if (this->metalView != nullptr)
    {
        SDL_Metal_DestroyView(this->metalView);
        this->metalView = nullptr;
    }
    if (this->window != nullptr)
    {
        SDL_DestroyWindow(this->window);
        this->window = nullptr;
    }

    pool->drain();
}

// ============================================================================
// STUB(M0): All GfxInterface methods below are no-ops. They are tagged with
// STUB(Mx) comments indicating which milestone will implement each. The grep
// pattern `grep "STUB(M" src/graphics/MetalBackend.cpp` lists all deferred
// work.
// ============================================================================

void MetalBackend::SetFogRange(f32 nearPlane, f32 farPlane)
{
    // M2: store in uniforms; flushed to GPU in SwapBuffers (and once at Init).
    this->uniforms.fogNear = nearPlane;
    this->uniforms.fogFar = farPlane;
}

void MetalBackend::SetFogColor(ZunColor color)
{
    // ZunColor is a u32 packed 0xAARRGGBB (COLOR_ALPHA_MASK etc.). The GL
    // backend unpacks to normalized floats in the same order (R=16, G=8, B=0,
    // A=24) — see WebGL.cpp SetFogColor. Match that here.
    this->uniforms.fogColor = ZunVec4(((color >> 16) & 0xFF) / 255.0f,
                                       ((color >> 8) & 0xFF) / 255.0f,
                                       ((color >> 0) & 0xFF) / 255.0f,
                                       ((color >> 24) & 0xFF) / 255.0f);
}

void MetalBackend::ToggleVertexAttribute(u8 attr, bool enable)
{
    // STUB(M3): ToggleVertexAttribute — configure vertex descriptor / pipeline
    // The vertex descriptor is currently baked into the pipeline at Init time;
    // M3 will make it dynamic when SetAttributePointer is implemented.
    (void)attr;
    (void)enable;
}

void MetalBackend::SetAttributePointer(VertexAttributeArrays attr, std::size_t stride, void *ptr)
{
    // STUB(M3): SetAttributePointer — record CPU pointer + stride; copy to a
    // Shared storage mode MTLBuffer at Draw() time.
    (void)attr;
    (void)stride;
    (void)ptr;
}

void MetalBackend::SetColorOp(TextureOpComponent component, ColorOp op)
{
    // M2: colorOp is a single int uniform consumed by the fragment shader.
    // The component argument is ignored on the GL backend too — EoSD only
    // uses the RGB path.
    (void)component;
    this->uniforms.colorOp = (i32)op;
}

void MetalBackend::SetTextureFactor(ZunColor factor)
{
    // M2: envDiffuse uniform (the GL backend calls this "envDiffuse"; the
    // shader multiplies fragArg2 by it). Same unpacking as SetFogColor.
    this->uniforms.envDiffuse = ZunVec4(((factor >> 16) & 0xFF) / 255.0f,
                                         ((factor >> 8) & 0xFF) / 255.0f,
                                         ((factor >> 0) & 0xFF) / 255.0f,
                                         ((factor >> 24) & 0xFF) / 255.0f);
}

void MetalBackend::SetTransformMatrix(TransformMatrix type, const ZunMatrix &matrix)
{
    // M2: route to the right slot in the uniforms struct. The GL backend's
    // matrixUniformEnum maps MATRIX_MODEL and MATRIX_VIEW both to MODELVIEW
    // (EoSD never sets them independently); mirror that here.
    switch (type)
    {
    case MATRIX_MODEL:
    case MATRIX_VIEW:
        this->uniforms.modelviewMatrix = matrix;
        break;
    case MATRIX_PROJECTION:
        this->uniforms.projectionMatrix = matrix;
        break;
    case MATRIX_TEXTURE:
        this->uniforms.textureMatrix = matrix;
        break;
    }
}

void MetalBackend::SetTextureFilter()
{
    // STUB(M4): SetTextureFilter — create/swap sampler state
}

void MetalBackend::GetViewport(u32 *viewport)
{
    // STUB(M5): GetViewport — return cached viewport (x,y,w,h)
}

void MetalBackend::GetDepthRange(f32 *depthRange)
{
    // STUB(M5): GetDepthRange — return cached near/far
}

void MetalBackend::SetViewport(i32 x, i32 y, i32 width, i32 height)
{
    // STUB(M5): SetViewport — set on render encoder at draw time
}

void MetalBackend::SetDepthRange(f32 nearPlane, f32 farPlane)
{
    // STUB(M5): SetDepthRange — setDepthClipPlane on render encoder
}

void MetalBackend::Enable(Capabilities cap)
{
    // STUB(M5): Enable — translate to depth/blend state on next pipeline
}

bool MetalBackend::HasError()
{
    // STUB(M0): HasError — no error tracking yet
    return false;
}

void MetalBackend::SetBlendMode(BlendMode mode)
{
    // STUB(M5): SetBlendMode — pipeline blend state
}

void MetalBackend::SetDepthMask(bool enable)
{
    // STUB(M5): SetDepthMask — depth stencil state
}

void MetalBackend::SetDepthFunc(DepthFunc func)
{
    // STUB(M5): SetDepthFunc — depth stencil state
}

void MetalBackend::SetClearDepth(f32 depth)
{
    this->clearDepth = depth;
}

void MetalBackend::SetClearColor(f32 r, f32 g, f32 b, f32 a)
{
    this->clearColor[0] = r;
    this->clearColor[1] = g;
    this->clearColor[2] = b;
    this->clearColor[3] = a;
}

void MetalBackend::Clear(u32 clearBits)
{
    // M1: defer the actual clear to SwapBuffers(). The game calls Clear()
    // multiple times per frame — once with color|depth at frame start, and
    // mid-frame depth-only clears during the draw chain. Metal can't cheaply
    // clear mid-pass, so we OR the requested bits and apply them once at pass
    // open. This is sufficient for M1's "solid color in window" success
    // criterion. M5 will revisit mid-frame clears if the game needs them.
    this->pendingClearBits |= clearBits;
}

GfxTextureHandle MetalBackend::CreateTexture()
{
    // STUB(M4): CreateTexture — allocate MTLTexture, return id handle
    GfxTextureHandle handle(this->nextTextureId++);
    return handle;
}

void MetalBackend::BindTexture(GfxTextureHandle handle)
{
    // STUB(M4): BindTexture — record for next argument table set
}

void MetalBackend::DeleteTexture(GfxTextureHandle handle)
{
    // STUB(M4): DeleteTexture — release MTLTexture
}

void MetalBackend::SetTextureImage(u32 width, u32 height, PixelFormat fmt, PixelDataType type, const void *data)
{
    // STUB(M4): SetTextureImage — create texture with pixel format mapping
}

void MetalBackend::SetTextureSubImage(i32 xoffset, i32 yoffset, i32 width, i32 height, const void *data)
{
    // STUB(M5): SetTextureSubImage — blit/replace region
}

void MetalBackend::ReadPixels(i32 x, i32 y, i32 width, i32 height, const void *pixels)
{
    // STUB(M5): ReadPixels — getBytes on drawable texture
}

void MetalBackend::Draw(PrimitiveType type, i32 start, i32 count)
{
    // STUB(M3): Draw — drawPrimitives on render encoder
}

void MetalBackend::SwapBuffers()
{
    // M2: open the frame's render pass (clearing with the cached values), bind
    // the render pipeline + depth-stencil state + uniform buffer, then close
    // and present. No draws are recorded yet — M3 will land drawPrimitives
    // between the setRenderPipelineState call and endEncoding. This still
    // verifies the full present pipeline: nextDrawable -> render pass (clear)
    // -> bind pipeline -> endEncoding -> presentDrawable -> commit.
    NS::AutoreleasePool *pool = NS::AutoreleasePool::alloc()->init();

    // Keep the layer's drawableSize in sync with the window. The game window
    // is fixed-size, but this is cheap and handles fullscreen transitions.
    int w = 0, h = 0;
    SDL_Metal_GetDrawableSize(this->window, &w, &h);
    if (w > 0 && h > 0)
    {
        this->layer->setDrawableSize(CGSizeMake(w, h));
    }

    // Flush CPU-side uniform updates into the GPU-visible buffer before
    // encoding. Shared storage mode = no blit needed; the GPU reads the same
    // memory the CPU just wrote. (If we ever move the uniform buffer to
    // Managed storage, this is where a blit would go — but Shared is correct
    // on Apple Silicon unified memory.)
    this->FlushUniforms();

    // Acquire the drawable for this frame. nextDrawable blocks on the CPU
    // until a drawable is available from the pool (max 2 in flight).
    this->currentDrawable = this->layer->nextDrawable();
    if (this->currentDrawable == nullptr)
    {
        utils::DebugPrint2("MetalBackend: nextDrawable returned null");
        this->pendingClearBits = 0;
        pool->drain();
        return;
    }

    this->currentCommandBuffer = this->commandQueue->commandBuffer();
    this->currentCommandBuffer->setLabel(NS::String::string("th06 frame", NS::UTF8StringEncoding));

    // Reuse the persistent depth texture across frames; (re)allocate if the
    // drawable size has changed. M1 allocated a throwaway per-frame; M2 keeps
    // one alive for the backend's lifetime and only reallocates on resize.
    this->EnsureDepthTexture((NS::UInteger)w, (NS::UInteger)h);

    MTL::RenderPassDescriptor *desc = MTL::RenderPassDescriptor::renderPassDescriptor();
    desc->setRenderTargetWidth((NS::UInteger)w);
    desc->setRenderTargetHeight((NS::UInteger)h);

    // Color attachment 0 = the drawable's texture. Load=Clear bakes the clear
    // value into the pass; Store=Store writes the result back for presentation.
    // If no color clear was requested this frame, Load=Load preserves prior
    // contents (M1 always clears color, so this branch is mostly defensive).
    MTL::RenderPassColorAttachmentDescriptor *colorAtt = desc->colorAttachments()->object(0);
    colorAtt->setTexture(this->currentDrawable->texture());
    if (this->pendingClearBits & CLEAR_COLOR_BUFFER)
    {
        colorAtt->setLoadAction(MTL::LoadActionClear);
        colorAtt->setClearColor(MTL::ClearColor::Make(this->clearColor[0], this->clearColor[1],
                                                        this->clearColor[2], this->clearColor[3]));
    }
    else
    {
        colorAtt->setLoadAction(MTL::LoadActionLoad);
    }
    colorAtt->setStoreAction(MTL::StoreActionStore);

    // Depth attachment = persistent depth texture. Even if the game didn't
    // request a depth clear this frame, the attachment must be present for
    // the depth-stencil state (set on the encoder below) to take effect.
    // Load=Clear when CLEAR_DEPTH_BUFFER was requested, else Load=Load to
    // preserve prior contents. Store=DontCare — we never read back the depth
    // texture, and discarding at pass end saves bandwidth.
    if (this->depthTexture != nullptr)
    {
        MTL::RenderPassDepthAttachmentDescriptor *depthAtt = desc->depthAttachment();
        depthAtt->setTexture(this->depthTexture);
        if (this->pendingClearBits & CLEAR_DEPTH_BUFFER)
        {
            depthAtt->setLoadAction(MTL::LoadActionClear);
            depthAtt->setClearDepth(this->clearDepth);
        }
        else
        {
            depthAtt->setLoadAction(MTL::LoadActionLoad);
        }
        depthAtt->setStoreAction(MTL::StoreActionDontCare);
    }

    // renderCommandEncoder() returns an autoreleased (+0) object — do NOT
    // release() it; the frame pool's drain() handles it. Keeping a raw
    // pointer within pool scope is the correct lifetime model.
    this->currentRenderEncoder = this->currentCommandBuffer->renderCommandEncoder(desc);
    this->currentRenderEncoder->setLabel(NS::String::string("th06 main pass", NS::UTF8StringEncoding));

    // M2: bind the render pipeline, depth-stencil state, and uniform buffer.
    // No draws are recorded yet (M3), but the encoder is now in a valid state
    // to receive drawPrimitives calls — the bindings persist for the rest of
    // the pass.
    if (this->pipelineState != nullptr)
    {
        this->currentRenderEncoder->setRenderPipelineState(this->pipelineState);
    }
    if (this->depthStencilState != nullptr)
    {
        this->currentRenderEncoder->setDepthStencilState(this->depthStencilState);
    }
    if (this->uniformBuffer != nullptr)
    {
        // Bind at buffer index 0 — matches the MSL `buffer(0)` binding on
        // both vertex and fragment stages.
        this->currentRenderEncoder->setVertexBuffer(this->uniformBuffer, 0, 0);
        this->currentRenderEncoder->setFragmentBuffer(this->uniformBuffer, 0, 0);
    }

    this->currentRenderEncoder->endEncoding();
    this->currentRenderEncoder = nullptr;

    // renderPassDescriptor() returns an autoreleased (+0) object — do NOT
    // release() it; the frame pool's drain() handles it.
    desc = nullptr;

    this->currentCommandBuffer->presentDrawable(this->currentDrawable);
    this->currentCommandBuffer->commit();

    // Release per-frame state. The drawable's backing texture is now owned by
    // the command buffer until it completes; releasing our reference here lets
    // the layer recycle the drawable.
    //
    // commandBuffer() and nextDrawable() both return autoreleased (+0)
    // objects — do NOT release() them, the frame pool's drain() handles it.
    this->currentCommandBuffer = nullptr;
    this->currentDrawable = nullptr;

    // Reset for the next frame.
    this->pendingClearBits = 0;

    pool->drain();
}
